### ISSUE TITLE
README未更新

### ISSUE THREAD

**Issue by 3Golds** [AliyunContainerService/kube-eventer#10]
readme上面的deployment command用的还是`eventer`, 并没有更改为`kube-eventer`, 镜像版本也比较低, 建议和deploy/ 目录保持一致

**Comment by 3Golds** [comment]
我更新了下image的版本`registry.cn-beijing.aliyuncs.com/acs/eventer:v1.6.0-1f6e829-aliyun`, 执行文件又变成`eventer`了？？？

**Comment by ringtail** [comment]
Fixed
