### ISSUE TITLE
Kafka sink 使用host域名会导致访问超时

### ISSUE THREAD

**Issue by standup-jb** [AliyunContainerService/kube-eventer#105]
在使用kafka sink的时候，发现如果brokers配置的是ip+port是可以正常连接到kafka集群的。但是如果是配置的host+port则会有问题。
1.  配置的kafka sink如下
`- --sink=kafka:?brokers=storage7.test.lan&brokers=storage8.test.lan&insecuressl=true`
2. 配置了hostAlias 
`hostAliases:
      - ip : "192.168.3.68"
        hostnames:
        - "storage8.test.lan"
      - ip : "192.168.3.69"
        hostnames:
        - "storage9.test.lan"
      - ip : "192.168.3.70"
        hostnames:
        - "storage10.test.lan"`
3. 在启动后。进入到docker里面。ping storage7.test.lan是可以正常ping通的
4. 但是docker启动的日志错误，显示超时

**Comment by ringtail** [comment]
是在k8s中吗，看上去是网络问题

**Comment by standup-jb** [comment]
> 是在k8s中吗，看上去是网络问题

不是网络问题。我试了。通过ping host 可以ping通的。
