### ISSUE TITLE
[Proposal]webhook sinks watch configmap change

### ISSUE THREAD

**Issue by wind2008hxy** [AliyunContainerService/kube-eventer#111]
建议webhook 监听configmap变化，动态改变推送内容，无需手动delete pod来触发更新。或者k8s 特性支持？

**Comment by ringtail** [comment]
> 建议webhook 监听configmap变化，动态改变推送内容，无需手动delete pod来触发更新。或者k8s 特性支持？

具体是什么场景会用到？

**Comment by wind2008hxy** [comment]
例如configmap原来配置了两个webhook sink，现在改了configmap增加到三个webhook sink，这个时候需要触发kube eventer变化，必须要手动删一次pod（重新拉起）才能生效。
目标是监听configmap的变化，自动reload。

**Comment by ringtail** [comment]
> 例如configmap原来配置了两个webhook sink，现在改了configmap增加到三个webhook sink，这个时候需要触发kube eventer变化，必须要手动删一次pod（重新拉起）才能生效。
> 目标是监听configmap的变化，自动reload。

我可能会更倾向于保持现有的配置方式，hot reload的场景似乎不是那么迫切。

**Comment by wind2008hxy** [comment]
> > 例如configmap原来配置了两个webhook sink，现在改了configmap增加到三个webhook sink，这个时候需要触发kube eventer变化，必须要手动删一次pod（重新拉起）才能生效。
> > 目标是监听configmap的变化，自动reload。
> 
> 我可能会更倾向于保持现有的配置方式，hot reload的场景似乎不是那么迫切。

嗯嗯，我在使用过程一个需求。。。
