### ISSUE TITLE
有考虑用eventrouter替代吗？

### ISSUE THREAD

**Issue by wind2008hxy** [AliyunContainerService/kube-eventer#112]
fork eventrouter，开发现在支持的sink。
对上兼容node detect

**Comment by ringtail** [comment]
https://github.com/AliyunContainerService/kube-eventer/issues/7

**Comment by ringtail** [comment]
这个问题在很久之前就做了讨论，可以参考以前的帖子

**Comment by wind2008hxy** [comment]
> 这个问题在很久之前就做了讨论，可以参考以前的帖子

以前的讨论有查看，只是再问问。
现在还不考虑切换是吗？
或者换个问法，是否考虑重构呢？

**Comment by ringtail** [comment]
> > 这个问题在很久之前就做了讨论，可以参考以前的帖子
> 
> 以前的讨论有查看，只是再问问。
> 现在还不考虑切换是吗？
> 或者换个问法，是否考虑重构呢？

为什么要重构呢？kube-eventer的功能比eventrouter更多，另外两者定位基本一致，kube-eventer还有兼容的使命，有什么特别原因需要做切换吗

**Comment by wind2008hxy** [comment]
如果没有重构的计划，为了兼容，这部分不用切换
