### ISSUE TITLE
kubernetes_source 里面的watch可以考虑用retrywatcher替代

### ISSUE THREAD

**Issue by wind2008hxy** [AliyunContainerService/kube-eventer#113]
https://github.com/kubernetes/client-go/blob/master/tools/watch/retrywatcher.go

**Comment by jemygraw** [comment]
好像并不是很好用，总是报错，一直没找到问题。
低版本client-go(v12.0.0)
 retrywatcher.go:129] Watch failed: watching resources is not possible with this client (content-type: application/json)

高版本client-go(0.17.6)
E0615 16:54:32.619455   26879 retrywatcher.go:129] Watch failed: the server could not find the requested resource (get events.meta.k8s.io)

**Comment by jemygraw** [comment]
这个方法不是用来监听 Events的，而是用来监听对象变化的，所以没办法用在这个场景下的。@ringtail

**Comment by ringtail** [comment]
> 是用来监听 Events的，而是用来监听对象变化的，所以没办法用在这个场景下的。@ringtail

Got it!

**Comment by wind2008hxy** [comment]
哇哦

**Comment by wind2008hxy** [comment]
> 这个方法不是用来监听 Events的，而是用来监听对象变化的，所以没办法用在这个场景下的。
嗯
