### ISSUE TITLE
elasticsearch能不能增加level选项

### ISSUE THREAD

**Issue by qiang93** [AliyunContainerService/kube-eventer#117]
sink为elasticsearch添加level=Warning选项无效，可否支持一下？Normal级别event过于频繁了

**Comment by ringtail** [comment]
> sink为elasticsearch添加level=Warning选项无效，可否支持一下？Normal级别event过于频繁了

Hi man @rralcala, @qiang93 wants to set level filter on es sink. What's your opinion about it.

**Comment by rralcala** [comment]
I took a look and there aren't many log statements in the sink itself:
`common/elasticsearch/elastic2.go:	klog.Warningf("Failed to execute bulk operation to ElasticSearch: %v", err)
common/elasticsearch/elastic2.go:	klog.V(3).Infof("Failed to execute bulk operation to ElasticSearch on %s: %v", name, itm.Error)
common/elasticsearch/elastic6.go:	klog.Warningf("Failed to execute bulk operation to ElasticSearch: %v", err)
common/elasticsearch/elastic6.go:	klog.V(3).Infof("Failed to execute bulk operation to ElasticSearch on %s: %v", name, itm.Error)
common/elasticsearch/elasticsearch.go:	klog.Info("Configuring with AWS credentials..")
common/elasticsearch/elasticsearch.go:	klog.V(2).Infof("ElasticSearch sink configure successfully")
common/elasticsearch/elastic7.go:	klog.Warningf("Failed to execute bulk operation to ElasticSearch: %v", err)
common/elasticsearch/elastic7.go:	klog.V(3).Infof("Failed to execute bulk operation to ElasticSearch on %s: %v", name, itm.Error)
common/elasticsearch/aws.go:	klog.Fatalf("error getting aws credentials: %v", err)
common/elasticsearch/elastic5.go:	klog.Warningf("Failed to execute bulk operation to ElasticSearch: %v", err)
common/elasticsearch/elastic5.go:	klog.V(3).Infof("Failed to execute bulk operation to ElasticSearch on %s: %v", name, itm.Error)
sinks/elasticsearch/driver.go:	klog.Warningf("Failed to convert event to point: %v", err)
sinks/elasticsearch/driver.go:	klog.Warningf("Failed to export data to ElasticSearch sink: %v", err)
sinks/elasticsearch/driver.go:	klog.Warningf("Failed to flushing data to ElasticSearch sink: %v", err)
sinks/elasticsearch/driver.go:	klog.Warning("Failed to config ElasticSearch")
sinks/elasticsearch/driver.go:	klog.V(2).Info("ElasticSearch sink setup successfully")`

And if you look at them they're either errors or one time printouts (like during init).

So, if there are chatty logs they must be coming from the manager or other parts of the code.

The proposal is valid, but I don't think that the elasticsearch sink is the right place and it won't be beneficial either.

A eventer wide option for (Debug, Info (default) or warning) might be better.

**Comment by ringtail** [comment]
> I took a look and there aren't many log statements in the sink itself:
> 
> ```
> common/elasticsearch/elastic2.go:	klog.Warningf("Failed to execute bulk operation to ElasticSearch: %v", err)
> common/elasticsearch/elastic2.go:	klog.V(3).Infof("Failed to execute bulk operation to ElasticSearch on %s: %v", name, itm.Error)
> common/elasticsearch/elastic6.go:	klog.Warningf("Failed to execute bulk operation to ElasticSearch: %v", err)
> common/elasticsearch/elastic6.go:	klog.V(3).Infof("Failed to execute bulk operation to ElasticSearch on %s: %v", name, itm.Error)
> common/elasticsearch/elasticsearch.go:	klog.Info("Configuring with AWS credentials..")
> common/elasticsearch/elasticsearch.go:	klog.V(2).Infof("ElasticSearch sink configure successfully")
> common/elasticsearch/elastic7.go:	klog.Warningf("Failed to execute bulk operation to ElasticSearch: %v", err)
> common/elasticsearch/elastic7.go:	klog.V(3).Infof("Failed to execute bulk operation to ElasticSearch on %s: %v", name, itm.Error)
> common/elasticsearch/aws.go:	klog.Fatalf("error getting aws credentials: %v", err)
> common/elasticsearch/elastic5.go:	klog.Warningf("Failed to execute bulk operation to ElasticSearch: %v", err)
> common/elasticsearch/elastic5.go:	klog.V(3).Infof("Failed to execute bulk operation to ElasticSearch on %s: %v", name, itm.Error)
> sinks/elasticsearch/driver.go:	klog.Warningf("Failed to convert event to point: %v", err)
> sinks/elasticsearch/driver.go:	klog.Warningf("Failed to export data to ElasticSearch sink: %v", err)
> sinks/elasticsearch/driver.go:	klog.Warningf("Failed to flushing data to ElasticSearch sink: %v", err)
> sinks/elasticsearch/driver.go:	klog.Warning("Failed to config ElasticSearch")
> sinks/elasticsearch/driver.go:	klog.V(2).Info("ElasticSearch sink setup successfully")
> ```
> 
> And if you look at them they're either errors or one time printouts (like during init).
> 
> So, if there are chatty logs they must be coming from the manager or other parts of the code.
> 
> The proposal is valid, but I don't think that the elasticsearch sink is the right place and it won't be beneficial either.
> 
> A eventer wide option for (Debug, Info (default) or warning) might be better.

I'm sorry I didn't explain clearly. Level filter means to filter kubernetes events when emitted to es.  The feature is direct. But I think es should be the place of all events instead of part of them.

**Comment by rralcala** [comment]
I agree with you @ringtail , there is a lot of value on recording all the events

elasticsearch is capable of handling large amounts of events and still be able to query very fast for only the warnings if needed.

Also, if we decide to move forward, this sounds like a feature that should be independent of the sink.
