### ISSUE TITLE
webhook配置获取不到事件信息

### ISSUE THREAD

**Issue by hbzhu** [AliyunContainerService/kube-eventer#119]
根据webhook配置示例configmap
data:
  content: >-
    { "msgtype": "text",
      "text": {"content":"EventType:{{ .Type }}\nEventKind:{{ .InvolvedObject.Kind }}\nEventReason:{{ .Reason }}\nEventTime:{{ .EventTime }}\nEventMessage:{{ .Message }}"},
      "markdown": {"title":"","text":""}
    }

钉钉没有获取到推送的事件信息，pod日志可以正常获取到事件，但是没有推送信息
不理解的是content字段应该是必须的，但是消息的body也包含有content字段

**Comment by ringtail** [comment]
> 根据webhook配置示例configmap
> data:
> content: >-
> { "msgtype": "text",
> "text": {"content":"EventType:{{ .Type }}\nEventKind:{{ .InvolvedObject.Kind }}\nEventReason:{{ .Reason }}\nEventTime:{{ .EventTime }}\nEventMessage:{{ .Message }}"},
> "markdown": {"title":"","text":""}
> }
> 
> 钉钉没有获取到推送的事件信息，pod日志可以正常获取到事件，但是没有推送信息
> 不理解的是content字段应该是必须的，但是消息的body也包含有content字段

v1.2.0-484d9cd-aliyun 可以试下这个版本，上一个Tag的主分支有一个custom webhook过滤的bug，已经修复

**Comment by hbzhu** [comment]
我更新了v1.2.0-484d9cd-aliyun，已经可以获取到推送消息了，非常感谢！
EventTime:0001-01-01 00:00:00 +0000 UTC ，这个情况是模板设置问题吗？

**Comment by ringtail** [comment]
@NUCsimple Pls check the eventTime.

**Comment by NUCsimple** [comment]
@hbzhu 改下模板，模板中的EventTime可以指定成这样："EventTime": "{{ .LastTimestamp }}"

**Comment by hbzhu** [comment]
@NUCsimple 谢谢，已经改成这个字段了，你有遇到message显示不全的问题吗，好像被截断了一样

**Comment by ringtail** [comment]
> @hbzhu 改下模板，模板中的EventTime可以指定成这样："EventTime": "{{ .LastTimestamp }}"

没有问题后麻烦修改下文档

**Comment by hbzhu** [comment]
@ringtail @NUCsimple 时间改为"EventTime": "{{ .LastTimestamp }}" 确定可以正常显示时间

**Comment by NUCsimple** [comment]
> > @hbzhu 改下模板，模板中的EventTime可以指定成这样："EventTime": "{{ .LastTimestamp }}"
> 
> 没有问题后麻烦修改下文档@NUCsimple

ok
