### ISSUE TITLE
写入到kafka ,pod无法启动，topic已经提前建好

### ISSUE THREAD

**Issue by zxx287856774** [AliyunContainerService/kube-eventer#12]
Failed to create {"kafka {      false brokers=10.204.57.32:9092&brokers=10.204.57.33:9092&brokers=10.204.57.34:9092&eventstopic=eventstopic" }} sink: Sink not recognized: "kafka
F0720 13:02:41.973843       1 eventer.go:90] No available sink to use
---
yaml文件。
---
command:
            - /kube-eventer
            - "--source=kubernetes:https://kubernetes.default"
            - --sink="kafka:?brokers=10.204.57.32:9092&brokers=10.204.57.33:9092&brokers=10.204.57.34:9092&eventstopic=eventstopic"
----
写错了吗/

**Comment by ringtail** [comment]
@stormgbs @jiazhiguang Pls check this issue.

**Comment by jiazhiguang** [comment]
> ## Failed to create {"kafka { false brokers=10.204.57.32:9092&brokers=10.204.57.33:9092&brokers=10.204.57.34:9092&eventstopic=eventstopic" }} sink: Sink not recognized: "kafka
> F0720 13:02:41.973843 1 eventer.go:90] No available sink to use
> ## yaml文件。
> ## command:
> - /kube-eventer
> - "--source=kubernetes:https://kubernetes.default"
> - --sink="kafka:?brokers=10.204.57.32:9092&brokers=10.204.57.33:9092&brokers=10.204.57.34:9092&eventstopic=eventstopic"
> 写错了吗/

Remove the double quotes in the `--sink` argument, the correct way should be like this:
```
- --sink=kafka:?brokers=10.204.57.32:9092&brokers=10.204.57.33:9092&brokers=10.204.57.34:9092&eventstopic=eventstopic
```

**Comment by stormgbs** [comment]
Fixed in PR: https://github.com/AliyunContainerService/kube-eventer/pull/15
