### ISSUE TITLE
webhook方式message字段显示只有前部分

### ISSUE THREAD

**Issue by hbzhu** [AliyunContainerService/kube-eventer#121]
使用webhook方式，message的长度是否有限制？

使用dingtalk可以完整的显示message的信息，这个和我get evnet出现的信息一致；

使用webhook，message字段只能显示前面部分信息，比如下列信息

Failed create pod sandbox: rpc error: code = Unknown desc = failed to start sandbox container for pod 
只显示到这，后半部分不显示了
"xxxxxxxx": Error response from daemon: OCI runtime create failed: container_linux.go:346: starting container process caused "process_linux.go:449: container init caused \"process_linux.go:438: writing syncT 'resume' caused \\\"write init-p: broken pipe\\\"\"": unknown

并且message后半部分新增的其他字段，比如EventEventAction都无法显示

**Comment by NUCsimple** [comment]
是否有加过滤字段呢？

**Comment by hbzhu** [comment]
@NUCsimple 
{
        "msgtype": "text",
        "text": {
            "content": "EventCluster: Dev-k8s\nEventType: {{ .Type }}\nEventKind: {{ .InvolvedObject.Kind }}\nEventNamespace: {{ .InvolvedObject.Namespace }}\nEventName: {{ .InvolvedObject.Name }}\nEventSource: {{ .Source }}\nEventReason: {{ .Reason }}\nEventTime: {{ .LastTimestamp }}\nEventMessage: {{ .Message }}\nEventAction: {{ .Action }}\nEventReportingController: {{ .ReportingController }}\nEventReportingInstance: {{ .ReportingInstance }}"
       }
}

这是我的模板信息

我发现，normal的没有问题，出现warning就是截断字段，我后面尝试把message字段改为第一行，结果就只显示message信息的前半部分，比如

EventTime: 2020-06-16 18:00:52 +0800 CST
EventMessage: Failed create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container

**Comment by NUCsimple** [comment]
ok

**Comment by NUCsimple** [comment]
你换个其他的webhook试下呢？比如wechart  or slack

**Comment by hbzhu** [comment]
@NUCsimple 我是使用的企业微信的群聊机器人，我好像发现是什么原因了，我直接使用微信机器人发送   
{
  "msgtype": "text",
  "text": {
    "content": "FailedCreatePodSandBox   kubelet, dev-worker02   Failed create pod sandbox: rpc error: code = Unknown desc = failed to start sandbox container for pod "xxx-daemon-1592320200-zq8wt": Error response from daemon: OCI runtime create failed: container_linux.go:344: starting container process caused "process_linux.go:424: container init caused \"process_linux.go:413: writing syncT 'resume' caused \\\"write init-p: broken pipe\\\"\"": unknown"
  }
}

这段报错的信息，提示输入的json数据不对，我发现是引号的问题导致了，只截取前面一段信息，暂时我没有办法去对获取信息里的引号做转义

同时我发现在使用webhook方式，钉钉机器人Warning的信息没有推送到，只要Normal信息

**Comment by hbzhu** [comment]
@NUCsimple 早上起来发现，使用webhook方式，钉钉机器人Warning的信息可以收取到，message也只是显示部分，我怀疑也是信息里带引号的原因
