### ISSUE TITLE
数据保存到mysql，如何自定义表名

### ISSUE THREAD

**Issue by standup-jb** [AliyunContainerService/kube-eventer#127]
如果使用sink mysql 。如何自定义表名。不希望数据库里面的表名叫kube-event, 想自己修改一下

**Comment by ringtail** [comment]
https://github.com/AliyunContainerService/kube-eventer/blob/master/common/mysql/mysql.go#L60

**Comment by ringtail** [comment]
支持表明设置，文档需要更新。
