### ISSUE TITLE
webhook默认模板EventMessage里面的引号没有转义，导致json解析不出来

### ISSUE THREAD

**Issue by 397334469** [AliyunContainerService/kube-eventer#129]
{    
    "EventType": "Warning",
    "EventKind": "Pod",
    "EventReason": "Failed",
    "EventTime": "0001-01-01 00:00:00 +0000 UTC",
    "EventMessage": "Failed to pull image "nginx:1.1.1.1": rpc error: code = Unknown desc = Error response from daemon: manifest for nginx:1.1.1.1 not found: manifest unknown: manifest unknown"
}

**Comment by ringtail** [comment]
@397334469 是指接收方没法收到完整json对吧。

**Comment by 397334469** [comment]
可以收到上面的内容，就如上方所示EventMessage，但双引号里面的双引号没有转义："Failed to pull image **_"nginx:1.1.1.1"_**: rpc error: code = Unknown desc = Error response from daemon: manifest for nginx:1.1.1.1 not found: manifest unknown: manifest unknown"

**Comment by doubledna** [comment]
{
	"EventType": "Warning",
	"EventKind": "Pod"
	"EventReason": "Failed",
	"EventTime": "0001-01-01 00:00:00 +0000 UTC",
	"EventMessage": "Failed to pull image "nginx:1.7.9-invalid": rpc error: code = Unknown desc = Error response from daemon: manifest for nginx:1.7.9-invalid not found"
}
我自定义的webhook接收的数据 "EventKind": "Pod"后面是没有逗号的 也导致解析错误 我看文档 给的格式也是丢失逗号的
想知道是从k8s中捕获数据就是如此 还是kube-eventer导致的

**Comment by ringtail** [comment]
> {
> "EventType": "Warning",
> "EventKind": "Pod"
> "EventReason": "Failed",
> "EventTime": "0001-01-01 00:00:00 +0000 UTC",
> "EventMessage": "Failed to pull image "nginx:1.7.9-invalid": rpc error: code = Unknown desc = Error response from daemon: manifest for nginx:1.7.9-invalid not found"
> }
> 我自定义的webhook接收的数据 "EventKind": "Pod"后面是没有逗号的 也导致解析错误 我看文档 给的格式也是丢失逗号的
> 想知道是从k8s中捕获数据就是如此 还是kube-eventer导致的

麻烦贴一下版本号

**Comment by AEGQ** [comment]
@397334469 请教下，这个问题有解决么，遇到相同问题 :)

**Comment by ringtail** [comment]
Fix by #158

**Comment by ringtail** [comment]
> @397334469 请教下，这个问题有解决么，遇到相同问题 :)

使用PR中的版本，已经修复了这个问题

**Comment by AEGQ** [comment]
@ringtail 已验证有效，感谢 👍
