### ISSUE TITLE
是否可以开放针对某个namespace下的event推送

### ISSUE THREAD

**Issue by m198799** [AliyunContainerService/kube-eventer#133]
我们的一个k8s 中跑着pro pre test dev 环境使用钉钉进行推送event 但是非pro环境大量的event。
我配置了k8s role rolebinding 但是发现不可以使用
![image](https://user-images.githubusercontent.com/3634397/87026416-4a4b4900-c20e-11ea-8ef6-8a5bba0bb2a7.png)
![image](https://user-images.githubusercontent.com/3634397/87026437-520aed80-c20e-11ea-83ac-1d8f7ead5633.png)
![image](https://user-images.githubusercontent.com/3634397/87026468-5cc58280-c20e-11ea-8340-870d488af05a.png)

**Comment by m198799** [comment]
目前使用钉钉的的自定义关键字，但是太笨重了。

**Comment by ringtail** [comment]
@m198799 无需在rolebinding的部分切割，只需要在参数中配置监听的namespace即可，另外如果需要切割不同的用户，可以配置多个同类webhook，但是不同的namespace。

**Comment by m198799** [comment]
抱歉确实没有看到有相应的参数对应namespace，可否提供一下相关文档
