### ISSUE TITLE
默认发送消息的模板怎么修改

### ISSUE THREAD

**Issue by cool-ops** [AliyunContainerService/kube-eventer#144]
Level:Normal 
Kind:Pod 
Namespace:monitoring 
Name:kube-eventer-7c558664bb-k4xhn.1628068d5af3cae7 
Reason:Started 
Timestamp:2020-08-04 17:27:52 +0800 CST 
Message:Started container kube-eventer

默认的是这种类型，如何修改模板呢？

**Comment by ringtail** [comment]
如果需要的话，可以通过Generic Webhook的方式来修改。

**Comment by ringtail** [comment]
https://github.com/AliyunContainerService/kube-eventer/blob/master/docs/en/webhook-sink.md
