### ISSUE TITLE
sink 配置飞书的webhook,提示: failed to send event to WebHook sink,because of failed to send msg to sink, because the response code is 404

### ISSUE THREAD

**Issue by Pefeng** [AliyunContainerService/kube-eventer#154]
## configMap如下：
apiVersion: v1
data:
  content: '{ "msg_type": "text", "content": {"text": "EventType:{{ .Type }}\nEventKind:{{
    .InvolvedObject.Kind }}\nEventReason:{{ .Reason }}\nEventTime:{{ .LastTimestamp
    }}\nEventMessage:{{ .Message }}"} }'
kind: ConfigMap
  name: custom-webhook-body
  namespace: kube-system

**Comment by ringtail** [comment]
because the response code is 404。可能要检查下远端的hook地址是否存在

**Comment by jicki** [comment]
> ## configMap如下：
> apiVersion: v1
> data:
> content: '{ "msg_type": "text", "content": {"text": "EventType:{{ .Type }}\nEventKind:{{
> .InvolvedObject.Kind }}\nEventReason:{{ .Reason }}\nEventTime:{{ .LastTimestamp
> }}\nEventMessage:{{ .Message }}"} }'
> kind: ConfigMap
> name: custom-webhook-body
> namespace: kube-system

请问一下你这边有没有配置好这个飞书吗

**Comment by Pefeng** [comment]
有配置好飞书的webhook的，直接用curl都可以调用的 
![image](https://user-images.githubusercontent.com/31119654/100975484-0d933c00-3579-11eb-8b4c-250ee46f9346.png)

**Comment by ringtail** [comment]
> 有配置好飞书的webhook的，直接用curl都可以调用的
> ![image](https://user-images.githubusercontent.com/31119654/100975484-0d933c00-3579-11eb-8b4c-250ee46f9346.png)

我这边没有飞书的环境，是否可以加入到开发者群，我们交互式的看下

**Comment by jicki** [comment]
> 有配置好飞书的webhook的，直接用curl都可以调用的
> ![image](https://user-images.githubusercontent.com/31119654/100975484-0d933c00-3579-11eb-8b4c-250ee46f9346.png)

呃请问一下这个 configmap 的信息就是如上面那个吗？？
我这边配置好像也是提示你这个错误 404

**Comment by Pefeng** [comment]
> > 有配置好飞书的webhook的，直接用curl都可以调用的
> > ![image](https://user-images.githubusercontent.com/31119654/100975484-0d933c00-3579-11eb-8b4c-250ee46f9346.png)
> 
> 呃请问一下这个 configmap 的信息就是如上面那个吗？？
> 我这边配置好像也是提示你这个错误 404

是的，就是关联上面自定义的configmap

**Comment by Pefeng** [comment]
> > 有配置好飞书的webhook的，直接用curl都可以调用的
> > ![image](https://user-images.githubusercontent.com/31119654/100975484-0d933c00-3579-11eb-8b4c-250ee46f9346.png)
> 
> 我这边没有飞书的环境，是否可以加入到开发者群，我们交互式的看下

curl -H 'Content-Type: application/json' https://open.feishu.cn/open-apis/bot/v2/hook/d91ea584-c7f9-46a2-8392-d46442403755 -d '{ "msg_type": "text", "content": {"text": "EventType:{{ .Type }}\nEventKind:{{ .InvolvedObject.Kind }}\nEventReason:{{ .Reason }}\nEventTime:{{ .LastTimestamp }}\nEventMessage:{{ .Message }}"} }'
{"Extra":null,"StatusCode":0,"StatusMessage":"success"}

**Comment by langhuadb** [comment]
> > > 有配置好飞书的webhook的，直接用curl都可以调用的
> > > ![image](https://user-images.githubusercontent.com/31119654/100975484-0d933c00-3579-11eb-8b4c-250ee46f9346.png)
> > 
> > 
> > 呃请问一下这个 configmap 的信息就是如上面那个吗？？
> > 我这边配置好像也是提示你这个错误 404
> 
> 是的，就是关联上面自定义的configmap

这个问题解决了嘛，我这边也是404
![image](https://user-images.githubusercontent.com/47592849/127255162-07e31242-a23a-463d-80e3-b06b6ebc1379.png)
![image](https://user-images.githubusercontent.com/47592849/127255293-6b5b0bb9-bfd4-4609-bbab-749a36625cb6.png)
![image](https://user-images.githubusercontent.com/47592849/127255320-af8de5f1-b15f-461c-a695-2c106d00c531.png)

**Comment by ringtail** [comment]
> > > > 有配置好飞书的webhook的，直接用curl都可以调用的
> > > > ![image](https://user-images.githubusercontent.com/31119654/100975484-0d933c00-3579-11eb-8b4c-250ee46f9346.png)
> > > 
> > > 
> > > 呃请问一下这个 configmap 的信息就是如上面那个吗？？
> > > 我这边配置好像也是提示你这个错误 404
> > 
> > 
> > 是的，就是关联上面自定义的configmap
> 
> 这个问题解决了嘛，我这边也是404
> ![image](https://user-images.githubusercontent.com/47592849/127255162-07e31242-a23a-463d-80e3-b06b6ebc1379.png)
> ![image](https://user-images.githubusercontent.com/47592849/127255293-6b5b0bb9-bfd4-4609-bbab-749a36625cb6.png)
> ![image](https://user-images.githubusercontent.com/47592849/127255320-af8de5f1-b15f-461c-a695-2c106d00c531.png)

麻烦看下是否是URL中缺少了`？`

**Comment by langhuadb** [comment]
> > > > > 有配置好飞书的webhook的，直接用curl都可以调用的
> > > > > ![image](https://user-images.githubusercontent.com/31119654/100975484-0d933c00-3579-11eb-8b4c-250ee46f9346.png)
> > > > 
> > > > 
> > > > 呃请问一下这个 configmap 的信息就是如上面那个吗？？
> > > > 我这边配置好像也是提示你这个错误 404
> > > 
> > > 
> > > 是的，就是关联上面自定义的configmap
> > 
> > 
> > 这个问题解决了嘛，我这边也是404
> > ![image](https://user-images.githubusercontent.com/47592849/127255162-07e31242-a23a-463d-80e3-b06b6ebc1379.png)
> > ![image](https://user-images.githubusercontent.com/47592849/127255293-6b5b0bb9-bfd4-4609-bbab-749a36625cb6.png)
> > ![image](https://user-images.githubusercontent.com/47592849/127255320-af8de5f1-b15f-461c-a695-2c106d00c531.png)
> 
> 麻烦看下是否是URL中缺少了`？`

飞书的机器人没有 ”?“,需要加在哪里呢，这个机器人我测过了直接curl是通的

**Comment by langhuadb** [comment]
![image](https://user-images.githubusercontent.com/47592849/127259701-fb896d27-2670-4d7a-9d7f-14111e50b370.png)

**Comment by langhuadb** [comment]
> > > > > 有配置好飞书的webhook的，直接用curl都可以调用的
> > > > > ![image](https://user-images.githubusercontent.com/31119654/100975484-0d933c00-3579-11eb-8b4c-250ee46f9346.png)
> > > > 
> > > > 
> > > > 呃请问一下这个 configmap 的信息就是如上面那个吗？？
> > > > 我这边配置好像也是提示你这个错误 404
> > > 
> > > 
> > > 是的，就是关联上面自定义的configmap
> > 
> > 
> > 这个问题解决了嘛，我这边也是404
> > ![image](https://user-images.githubusercontent.com/47592849/127255162-07e31242-a23a-463d-80e3-b06b6ebc1379.png)
> > ![image](https://user-images.githubusercontent.com/47592849/127255293-6b5b0bb9-bfd4-4609-bbab-749a36625cb6.png)
> > ![image](https://user-images.githubusercontent.com/47592849/127255320-af8de5f1-b15f-461c-a695-2c106d00c531.png)
> 
> 麻烦看下是否是URL中缺少了`？`

感谢提示，解决了
