### ISSUE TITLE
sink为webhook时，使用springboot项目自定义一个webhook结束，请求的body的json格式是错误的

### ISSUE THREAD

**Issue by somta** [AliyunContainerService/kube-eventer#161]
默认的请求格式的body格式是错误的，EventKind后面是缺少一个逗号的，如下：
{
	"EventType": "Normal",
	"EventKind": "Pod"
	"EventReason": "Started",
	"EventTime": "0001-01-01 00:00:00 +0000 UTC",
	"EventMessage": "Started container istio-proxy"
}

**Comment by ringtail** [comment]
请尝试用最新的版本，这个问题已经修复

**Comment by zxt620** [comment]
> 默认的请求格式的body格式是错误的，EventKind后面是缺少一个逗号的，如下：
> {
> "EventType": "Normal",
> "EventKind": "Pod"
> "EventReason": "Started",
> "EventTime": "0001-01-01 00:00:00 +0000 UTC",
> "EventMessage": "Started container istio-proxy"
> }

请问你是如何使用springboot自定义一个webhook的？我配置了一个普通的url，却接收不到事件信息

**Comment by ringtail** [comment]
> > 默认的请求格式的body格式是错误的，EventKind后面是缺少一个逗号的，如下：
> > {
> > "EventType": "Normal",
> > "EventKind": "Pod"
> > "EventReason": "Started",
> > "EventTime": "0001-01-01 00:00:00 +0000 UTC",
> > "EventMessage": "Started container istio-proxy"
> > }
> 
> 请问你是如何使用springboot自定义一个webhook的？我配置了一个普通的url，却接收不到事件信息

最新的版本有尝试过吗
