### ISSUE TITLE
使用自定义的webhook来接收时，如果message里面是带双引号的，会出现反序列化的问题

### ISSUE THREAD

**Issue by somta** [AliyunContainerService/kube-eventer#165]
如下，message中出现了双引号，会导致反序列化的时候失败
{
	"eventType": "Normal",
	"eventKind": "Pod",
        "namespace": "default",
        "podName": "s2i-jnlp-n40jc",
	"eventReason": "Pulled",
	"eventTime": "2020-12-28 19:50:46 +0800 CST",
	"eventMessage": "Container image "registry.harbor.yun.net:30002/ci-and-cd/jnlp-slave-s2i:1.0.2" already present on machine"
}

**Comment by ringtail** [comment]
需要自己进行转义

**Comment by somta** [comment]
那能否支持Content-Type：application/x-www-form-urlencoded类型呢？目前在header里面设置是无效的

**Comment by ringtail** [comment]
下面的sink是webhook类型的吗

**Comment by somta** [comment]
> 下面的sink是webhook类型的吗
是的，定义的sink如下
--sink=webhook:http://my_url:8080/v1/event/webhook2?level=Warning&method=POST&header=Content-Type=application/x-www-form-urlencoded&custom_body_configmap=custom-body&custom_body_configmap_namespace=study
header设置没有生效，使用的仍然是application/json的形式

**Comment by ringtail** [comment]
master版本已经解决
