### ISSUE TITLE
flask写的简单接口，curl POST没问题，kube-event配置该webhook报404

### ISSUE THREAD

**Issue by chaishiqi** [AliyunContainerService/kube-eventer#169]
RT，flask部分内容如下:

@app.route('/',methods=['POST'])
def hello_world():
    data=request.data.decode("utf-8")
    print(data)
    return 'send_success'

if __name__ == '__main__':
    app.run(host='0.0.0.0',port=9999,debug=True)

启动方式如下:

--sink=webhook:http://x.x.x.x:9999/&method=POST&level=Normal&header=contentType=application/json

然后收到消息报404
 Failed to send event to WebHook sink,because of failed to send msg to sink, because the response code is 404, body is : <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>404 Not Found</title>
<h1>Not Found</h1>
<p>The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.</p>

请教下自定义的接口需要注意什么事项么？

**Comment by ringtail** [comment]
--sink=webhook:http://x.x.x.x:9999?method=POST&level=Normal&header=contentType=application/json

**Comment by ringtail** [comment]
url query使用？隔开queryString和host
