### ISSUE TITLE
现在eventMessage里面有些message是带有回车符号的，在反序列化的时候，这类的message是无法解析的

### ISSUE THREAD

**Issue by somta** [AliyunContainerService/kube-eventer#170]
请求体如下
{
	"eventType": "Warning",
	"eventKind": "Node",
        "namespace": "",
        "podName": "cn-shi-wz9ahheh6upz4dxs",
	"eventReason": "OOMKilling",
	"eventTime": "2021-01-28 10:25:06 +0800 CST",
	"eventMessage": "(combined from similar events): Memory cgroup out of memory: Kill process 17761 (ilogtail) score 2007 or sacrifice child
Killed process 16286 (ilogtail) total-vm:1075692kB, anon-rss:520084kB, file-rss:10512kB, shmem-rss:0kB",
        "count": "51252"
}

**Comment by NUCsimple** [comment]
@somta  Which sink do you use?

**Comment by somta** [comment]
使用的 webhook
