### ISSUE TITLE
相比用prometheus采集信息，eventer采集的信息是不是更多？

### ISSUE THREAD

**Issue by wajika** [AliyunContainerService/kube-eventer#171]
我这里部署了prometheus和eventer，感觉eventer告警的事件多一点

**Comment by ringtail** [comment]
> 我这里部署了prometheus和eventer，感觉eventer告警的事件多一点

有所不同，k8s的逻辑是状态机，状态的变化会产生对应的事件，正常的状态转换为Normal事件，异常的状态为Warning事件。Prometheus更多的是资源指标类型的监控，两者不完全重合。但是对于我们普通的运维人员或者应用管理员而言，事件的报警一定是最先触发，相比资源告警而言也更丰富。因此，组合事件告警与资源告警可以覆盖基本全部的报警范围，而对于ChatOps等集成的场景而言，事件告警会更高效。

**Comment by ringtail** [comment]
对于详细的报警列表，可以参照这个开源项目，https://github.com/ringtail/kubernetes-events-generator

**Comment by ringtail** [comment]
不完全覆盖，但是覆盖常用的85%的报警场景

**Comment by wajika** [comment]
感谢解答

**Comment by KeithTt** [comment]
warning 事件确实有点多，我感觉这些事件基本上都没有告警的必要性..
