### ISSUE TITLE
能增加对于资源使用的告警吗？

### ISSUE THREAD

**Issue by wajika** [AliyunContainerService/kube-eventer#173]
比如说cpu、内存使用量过大等等。这样就可以抛弃prometheus了。

**Comment by ringtail** [comment]
> 比如说cpu、内存使用量过大等等。这样就可以抛弃prometheus了。

kube-eventer更多是作为事件的通道，而不是事件的产生源，对于CPU过大或者内存过大，可以通过调用metrics-server的接口进行封装，实现类似的逻辑

**Comment by wajika** [comment]
> > 比如说cpu、内存使用量过大等等。这样就可以抛弃prometheus了。
> 
> kube-eventer更多是作为事件的通道，而不是事件的产生源，对于CPU过大或者内存过大，可以通过调用metrics-server的接口进行封装，实现类似的逻辑

后续会增加这个功能吗？

**Comment by ringtail** [comment]
> > > 比如说cpu、内存使用量过大等等。这样就可以抛弃prometheus了。
> > 
> > 
> > kube-eventer更多是作为事件的通道，而不是事件的产生源，对于CPU过大或者内存过大，可以通过调用metrics-server的接口进行封装，实现类似的逻辑
> 
> 后续会增加这个功能吗？ 我觉得最好能整合一下，这样技术栈能统一，其实需求很简单，就是采集异常事件和资源信息。 两个都部署，这一套那一套有点杂。

目前还没有这方便的规划，如果需求比较明确，可以开启新的项目进行支持

**Comment by wajika** [comment]
好的，感谢回复。
