### ISSUE TITLE
是否可以实现在mysql的sink中添加label参数

### ISSUE THREAD

**Issue by serchaofan** [AliyunContainerService/kube-eventer#177]
是否可以实现mysql的kube_event表中添加字段label，然后可以在sink中指定label参数，用于区分不同环境的events，类似钉钉和微信sink的label参数。

镜像版本：kube-eventer-amd64:v1.2.0-484d9cd-aliyun

**Comment by ringtail** [comment]
可以提交一个PR来做支持
