### ISSUE TITLE
Add stdout sink / support promtail

### ISSUE THREAD

**Issue by varac** [AliyunContainerService/kube-eventer#181]
We're using promtail to aggregate logs so a sinple stdout sink would be perfect for promtail to gather the 
kube-eventer  logs - or do they already show up in the pod stdout log ?

**Comment by ringtail** [comment]
> We're using promtail to aggregate logs so a sinple stdout sink would be perfect for promtail to gather the
> kube-eventer logs - or do they already show up in the pod stdout log ?

I think a seperate log file would be better

**Comment by varac** [comment]
from https://12factor.net/logs:

> A twelve-factor app never concerns itself with routing or storage of its output stream. It should not attempt to write to or manage logfiles. Instead, each running process writes its event stream, unbuffered, to stdout

**Comment by varac** [comment]
@ringtail Why do you think a logfile is better ? Promtail could handle both log files and stdout, so I don't care too much at the end.

**Comment by ringtail** [comment]
> @ringtail Why do you think a logfile is better ? Promtail could handle both log files and stdout, so I don't care too much at the end.

I agree with you. Would you like to open a pr?
