### ISSUE TITLE
配置sls时发生Aliyun Metadata API Error: Status Code: 404

### ISSUE THREAD

**Issue by Zhuaiz** [AliyunContainerService/kube-eventer#183]
我估计是配置问题，但是没找到问题出在哪里
yaml如下
-------
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: kube-eventer
  name: kube-eventer
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-eventer
  template:
    metadata:
      labels:
        app: kube-eventer
      annotations:	
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      serviceAccount: kube-eventer
      containers:
        - image: registry.aliyuncs.com/acs/kube-eventer-amd64:v1.2.0-484d9cd-aliyun
          name: kube-eventer
          command:
            - "/kube-eventer"
            - "--source=kubernetes:https://kubernetes.default"
            ## .e.g,dingtalk sink demo
            - --sink=sls:https://cn-beijing-intranet.log.aliyuncs.com?project=k8s-log-c3da28bccf16b457ca7e2ace95e007293&logStore=k8s-event&topic=kube-eventer
          env:
          # If TZ is assigned, set the TZ value as the time zone
          - name: TZ
            value: "Asia/Shanghai" 
          volumeMounts:
            - name: localtime
              mountPath: /etc/localtime
              readOnly: true
            - name: zoneinfo
              mountPath: /usr/share/zoneinfo
              readOnly: true
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 250m
              memory: 512Mi
      volumes:
        - name: localtime
          hostPath:
            path: /etc/localtime
        - name: zoneinfo
          hostPath:
            path: /usr/share/zoneinfo
-------
第一次配置：
-------
I0407 11:44:56.872371       1 eventer.go:67] /kube-eventer --source=kubernetes:https://kubernetes.default --sink=sls:https://sls.aliyuncs.com?project=k8s-log-c3da28bccf16b457ca7e2ace95e007293&logStore=k8s-event&topic=kube-eventer
I0407 11:44:56.872547       1 eventer.go:68] kube-eventer version: v1.2.0 commit: 484d9cd
I0407 11:44:56.873693       1 eventer.go:94] Starting with SLSSink sink
I0407 11:44:56.873805       1 eventer.go:108] Starting eventer
I0407 11:44:56.873881       1 eventer.go:116] Starting eventer http service
I0407 11:45:00.000146       1 manager.go:102] Exporting 0 events
I0407 11:45:30.000155       1 manager.go:102] Exporting 6 events
E0407 11:45:30.039518       1 sls.go:286] failed to get RoleName,because of Aliyun Metadata API Error: Status Code: 404
2021/04/07 11:45:30 can not create sls client because of Aliyun Metadata API Error: Status Code: 404
------

第二次配置
------
I0407 11:50:45.255904       1 eventer.go:67] /kube-eventer --source=kubernetes:https://kubernetes.default --sink=sls:https://cn-beijing-intranet.log.aliyuncs.com?project=k8s-log-c3da28bccf16b457ca7e2ace95e007293&logStore=k8s-event&topic=kube-eventer
I0407 11:50:45.256081       1 eventer.go:68] kube-eventer version: v1.2.0 commit: 484d9cd
I0407 11:50:45.257202       1 eventer.go:94] Starting with SLSSink sink
I0407 11:50:45.257298       1 eventer.go:108] Starting eventer
I0407 11:50:45.257374       1 eventer.go:116] Starting eventer http service
I0407 11:51:00.000169       1 manager.go:102] Exporting 0 events
I0407 11:51:30.000145       1 manager.go:102] Exporting 0 events
I0407 11:52:00.000129       1 manager.go:102] Exporting 0 events
I0407 11:52:30.000146       1 manager.go:102] Exporting 0 events
I0407 11:53:00.000165       1 manager.go:102] Exporting 0 events
I0407 11:53:30.000135       1 manager.go:102] Exporting 0 events
I0407 11:54:00.000132       1 manager.go:102] Exporting 0 events
I0407 11:54:30.000145       1 manager.go:102] Exporting 0 events
I0407 11:55:00.000145       1 manager.go:102] Exporting 0 events
I0407 11:55:30.000144       1 manager.go:102] Exporting 1 events
E0407 11:55:30.019578       1 sls.go:286] failed to get RoleName,because of Aliyun Metadata API Error: Status Code: 404
2021/04/07 11:55:30 can not create sls client because of Aliyun Metadata API Error: Status Code: 404
-------

**Comment by ringtail** [comment]
没有配置AK相关信息

**Comment by Zhuaiz** [comment]
AK相关信息填写到哪里呢？
下面是给出的例子，没找到相应字段，，
顺便问下可以配置多个sink么，例如
          command:
            - "/kube-eventer"
            - "--source=kubernetes:https://kubernetes.default"
            - --sink=sls:https://cn-beijing-intranet.log.aliyuncs.com?project=k8s-log-c3da28bccf16b457ca7e2ace95e007293&logStore=k8s-event&topic=kube-eventer
            - --sink=wechat:?corp_id=xxx&corp_secret=xxx&agent_id=1000002&to_user=1&label=k8s-event&level=Warning
---
sls sink
This sink supports sls (Log Service of Alibaba Cloud). To use the sls sink add the following flag:

--sink=sls:<SLS_ENDPOINTL>&logStore=[your_logstore]&project=[your_project]&topic=[topic_for_log]
The following options are available:

project - Project of SLS instance.
logStore - logStore of SLS instance project.
topic - topic for every log sent to SLS.
For example:

--sink=sls:https://sls.aliyuncs.com?project=my_sls_project&logStore=my_sls_project_logStore&topic=k8s-cluster-dev

**Comment by ringtail** [comment]
@Zhuaiz Doc updated.
