### ISSUE TITLE
Kafka中接收到的message时间比当前时间慢八小时

### ISSUE THREAD

**Issue by 20100507** [AliyunContainerService/kube-eventer#184]
**message中的时间比当前时间慢8小时**
`{"EventValue":"{\n \"metadata\": {\n  \"name\": \"nginx-deployment-789b79d7c6-ng4w9.167371d3386d2b7c\",\n  \"namespace\": \"default\",\n  \"selfLink\": \"/api/v1/namespaces/default/events/nginx-deployment-789b79d7c6-ng4w9.167371d3386d2b7c\",\n  \"uid\": \"e3be090a-4342-4e8b-8937-3d6e11aeb826\",\n  \"resourceVersion\": \"9229717\",\n  \"creationTimestamp\": \"2021-04-07T02:17:23Z\",\n  \"managedFields\": [\n   {\n    \"manager\": \"kubelet\",\n    \"operation\": \"Update\",\n    \"apiVersion\": \"v1\",\n    \"time\": \"2021-04-07T02:17:23Z\",\n    \"fieldsType\": \"FieldsV1\",\n    \"fieldsV1\": {\n     \"f:count\": {},\n     \"f:firstTimestamp\": {},\n     \"f:involvedObject\": {\n      \"f:apiVersion\": {},\n      \"f:fieldPath\": {},\n      \"f:kind\": {},\n      \"f:name\": {},\n      \"f:namespace\": {},\n      \"f:resourceVersion\": {},\n      \"f:uid\": {}\n     },\n     \"f:lastTimestamp\": {},\n     \"f:message\": {},\n     \"f:reason\": {},\n     \"f:source\": {\n      \"f:component\": {},\n      \"f:host\": {}\n     },\n     \"f:type\": {}\n    }\n   }\n  ]\n },\n \"involvedObject\": {\n  \"kind\": \"Pod\",\n  \"namespace\": \"default\",\n  \"name\": \"nginx-deployment-789b79d7c6-ng4w9\",\n  \"uid\": \"c97cb69b-3735-4b76-98fa-31a35845c700\",\n  \"apiVersion\": \"v1\",\n  \"resourceVersion\": \"9229702\",\n  \"fieldPath\": \"spec.containers{nginx-con}\"\n },\n \"reason\": \"Pulled\",\n \"message\": \"Container image \\\"nginx:latest\\\" already present on machine\",\n \"source\": {\n  \"component\": \"kubelet\",\n  \"host\": \"xxxxxxxxx\"\n },\n \"firstTimestamp\": \"2021-04-07T02:17:23Z\",\n \"lastTimestamp\": \"2021-04-07T02:17:23Z\",\n \"count\": 1,\n \"type\": \"Normal\",\n \"eventTime\": null,\n \"reportingComponent\": \"\",\n \"reportingInstance\": \"\"\n}","EventTimestamp":"2021-04-07T02:17:23Z","EventTags":{"eventID":"e3be090a-4342-4e8b-8937-3d6e11aeb826","hostname":"xxx","pod_id":"c97cb69b-3735-4b76-98fa-31a35845c700","pod_name":"nginx-deployment-789b79d7c6-ng4w9"}}   nginx-deployment-789b79d7c6-ng4w9`

 目前不太清楚kube-event详细工作原理，当前kube-event容器的时间是正常的，运行的nginx的容器时间也是正常的。可能会是什么地方的原因呢？请教一下各位大神。

**Comment by ringtail** [comment]
@20100507 可以先看下event的原始时间是否是对的。
