### ISSUE TITLE
sink=sls 添加完AK相关环境变量后，404现象依然发生

### ISSUE THREAD

**Issue by Zhuaiz** [AliyunContainerService/kube-eventer#187]
#183 
I0422 14:04:25.178655       1 eventer.go:67] /kube-eventer --source=kubernetes:https://kubernetes.default -sink=sls:https://cn-beijing-intranet.log.aliyuncs.com?project=k8s-log-c3da28bccf16b457ca7e2ace95e007293&logStore=k8s-event&topic=kube-eventer
I0422 14:04:25.178892       1 eventer.go:68] kube-eventer version: v1.2.0 commit: 484d9cd
I0422 14:04:25.180007       1 eventer.go:94] Starting with SLSSink sink
I0422 14:04:25.180101       1 eventer.go:108] Starting eventer
I0422 14:04:25.180177       1 eventer.go:116] Starting eventer http service
I0422 14:04:30.000149       1 manager.go:102] Exporting 0 events
I0422 14:05:00.000133       1 manager.go:102] Exporting 0 events
I0422 14:05:30.000119       1 manager.go:102] Exporting 0 events
I0422 14:06:00.000125       1 manager.go:102] Exporting 0 events
I0422 14:06:30.000136       1 manager.go:102] Exporting 0 events
I0422 14:07:00.000132       1 manager.go:102] Exporting 0 events
I0422 14:07:30.000134       1 manager.go:102] Exporting 0 events
I0422 14:08:00.000132       1 manager.go:102] Exporting 0 events
I0422 14:08:30.000143       1 manager.go:102] Exporting 0 events
I0422 14:09:00.000119       1 manager.go:102] Exporting 1 events
E0422 14:09:00.037108       1 sls.go:286] failed to get RoleName,because of Aliyun Metadata API Error: Status Code: 404
2021/04/22 14:09:00 can not create sls client because of Aliyun Metadata API Error: Status Code: 404

是否需要在新的release版本上面运行？如何找到新的仓库镜像url，或者自己build的方法？

**Comment by ringtail** [comment]
@Zhuaiz 麻烦贴下你的模板

**Comment by Zhuaiz** [comment]
跟#183 一样
只是在环境变量里多了
env:
 - AccessKeyId: "xxx"
 - AccessKeySecret: "xxx"

**Comment by ringtail** [comment]
还需要补充一个地域的环境变量：RegionId

**Comment by Zhuaiz** [comment]
补充了地域的环境变量：RegionId，现象没有变化
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: '3'
  creationTimestamp: '2021-04-26T02:29:19Z'
  generation: 3
  labels:
    name: kube-eventer
      manager: kube-controller-manager
      operation: Update
      time: '2021-04-26T02:32:28Z'
  name: kube-eventer
  namespace: kube-system
  resourceVersion: '570202248'
  selfLink: /apis/apps/v1/namespaces/kube-system/deployments/kube-eventer
  uid: eed730f7-83ab-4693-bef0-eb06d469dd54
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: kube-eventer
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
      labels:
        app: kube-eventer
    spec:
      containers:
        - command:
            - /kube-eventer
            - '--source=kubernetes:https://kubernetes.default'
            - >-
              --sink=sls:https://cn-beijing-intranet.log.aliyuncs.com?project=k8s-log-c3da28bccf16b457ca7e2ace95e007293&logStore=k8s-event&topic=kube-eventer
          env:
            - name: TZ
              value: Asia/Shanghai
            - name: accessKeyId
              value: LTxxxxxxxxxxxxxfCcxxVo
            - name: accessKeySecret
              value: dxxxxxxxxxxxxxxxxxx3Bn
            - name: RegionId
              value: cn-beijing
          image: 'registry.aliyuncs.com/acs/kube-eventer-amd64:v1.2.0-484d9cd-aliyun'
          imagePullPolicy: IfNotPresent
          name: kube-eventer
          resources:
            limits:
              cpu: 250m
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 100Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /etc/localtime
              name: localtime
              readOnly: true
            - mountPath: /usr/share/zoneinfo
              name: zoneinfo
              readOnly: true
      dnsPolicy: ClusterFirstWithHostNet
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: kube-eventer
      serviceAccountName: kube-eventer
      terminationGracePeriodSeconds: 30
      volumes:
        - hostPath:
            path: /etc/localtime
            type: ''
          name: localtime
        - hostPath:
            path: /usr/share/zoneinfo
            type: ''
          name: zoneinfo

**Comment by ringtail** [comment]
AccessKeyId and AccessKeySecret

**Comment by Zhuaiz** [comment]
AccessKeyId和AccessKeySecret 大小写都试过了，现象依旧是这样，不知道如何追踪问题，，，

**Comment by ringtail** [comment]
> AccessKeyId和AccessKeySecret 大小写都试过了，现象依旧是这样，不知道如何追踪问题，，，

Clone下code，本地可以跑一下

**Comment by NUCsimple** [comment]
@Zhuaiz 您的kube-eventer容器是运行在哪里呢？虚拟机吗？

**Comment by Zhuaiz** [comment]
> @Zhuaiz 您的kube-eventer容器是运行在哪里呢？虚拟机吗？

ASK集群

**Comment by ringtail** [comment]
> > @Zhuaiz 您的kube-eventer容器是运行在哪里呢？虚拟机吗？
> 
> ASK集群

有试过最新的版本吗
