### ISSUE TITLE
OOMKilled 能否显示

### ISSUE THREAD

**Issue by ldd91** [AliyunContainerService/kube-eventer#189]
在我们的集群中出现 pod OOMKilled，但是 event 这边只能显示 BackOff，用户无法知道 BackOff 的真正原因，请问有什么比较好的方案吗？

**Comment by ringtail** [comment]
> 在我们的集群中出现 pod OOMKilled，但是 event 这边只能显示 BackOff，用户无法知道 BackOff 的真正原因，请问有什么比较好的方案吗？

需要结合NPD来使用。

**Comment by ldd91** [comment]
@ringtail  你好 NPD 指的是 Node Problem Detector 吗？有没有推荐的采集器。

**Comment by ldd91** [comment]
好的 感谢 我这边看下
