### ISSUE TITLE
failed to put events to sls,because of Aliyun API Error: Status Code: 401 Code: Unauthorized Message: denied by sts or ram, action: log:PostLogStoreLogs,

### ISSUE THREAD

**Issue by czhfe** [AliyunContainerService/kube-eventer#193]
使用sls做为sink，部署好以后报如下错误：
failed to put events to sls,because of Aliyun API Error: Status Code: 401 Code: Unauthorized Message: denied by sts or ram, action: log:PostLogStoreLogs

我使用的是阿里云主账号的AcessKey ID，这是不应该会出现权限问题的，请问一下这是哪块出问题了

**Comment by NUCsimple** [comment]
请问您的集群是托管集群还是专有集群呢？ @czhfe

**Comment by czhfe** [comment]
托管版集群拿来测的

**Comment by czhfe** [comment]
![image](https://user-images.githubusercontent.com/19341806/121000579-f568d780-c7bc-11eb-9707-caa14b1caf7f.png)
另外我 本地虚机自建集群拿来测试报这个错，貌似使用阿里云私有网络访问了，我把internal参数设置了false也没用

**Comment by NUCsimple** [comment]
请问您用的是本地构建的测试镜像，是吧？ @czhfe

**Comment by czhfe** [comment]
> 假设您用的是本地构建的测试镜像，是吧？@czhfe

不是的，使用的是这个示例里面的那个镜像，registry.aliyuncs.com/acs/kube-eventer-amd64:v1.2.0-484d9cd-aliyun


另外我在本地把代码拉下来，使用master分支最新代码编译，然后测试也存在问题

**Comment by NUCsimple** [comment]
集群版本是多少呢？ @czhfe

**Comment by czhfe** [comment]
1.18和1.20都测试过

**Comment by czhfe** [comment]
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-eventer
  namespace: kube-system
  labels:
    helm.sh/chart: kube-eventer-0.1.0
    app.kubernetes.io/name: kube-eventer
    app.kubernetes.io/instance: kube-eventer
    k8s-app: kube-eventer
    app.kubernetes.io/version: "1.2.0"
    app.kubernetes.io/managed-by: Helm
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kube-eventer
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - events
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube-eventer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-eventer
subjects:
  - kind: ServiceAccount
    name: kube-eventer
    namespace: kube-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-eventer
  namespace: kube-system
  labels:
    helm.sh/chart: kube-eventer-0.1.0
    app.kubernetes.io/name: kube-eventer
    app.kubernetes.io/instance: kube-eventer
    k8s-app: kube-eventer
    app.kubernetes.io/version: "1.2.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: kube-eventer
      app.kubernetes.io/instance: kube-eventer
      k8s-app: kube-eventer
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kube-eventer
        app.kubernetes.io/instance: kube-eventer
        k8s-app: kube-eventer
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      serviceAccountName: kube-eventer
      containers:
        - name: kube-eventer
          image: "registry.aliyuncs.com/acs/kube-eventer-amd64:v1.2.0-484d9cd-aliyun"
          imagePullPolicy: IfNotPresent
          command:
            - "/kube-eventer"
            - "--source=kubernetes:https://kubernetes.default"
            - "--sink=sls:https://sls.aliyuncs.com?project=k8slogs&logStore=kube-eventer-test&topic=k8s-monitor-test&internal=false&accessKeyId=xxx&accessKeySecret=xxx"
          env:
            - name: TZ
              value: "Asia/Shanghai"
            - name: RegionId
              value: "cn-hangzhou"
          volumeMounts:
            - name: localtime
              mountPath: /etc/localtime
              readOnly: true
            - name: zoneinfo
              mountPath: /usr/share/zoneinfo
              readOnly: true
          resources:
            limits:
              cpu: 500m
              memory: 250Mi
            requests:
              cpu: 100m
              memory: 100Mi
      volumes:
        - name: localtime
          hostPath:
            path: /etc/localtime
        - name: zoneinfo
          hostPath:
            path: /usr/share/zoneinfo

**Comment by NUCsimple** [comment]
@czhfe 可以参考这个PR重新配置下eventer的yaml。
https://github.com/AliyunContainerService/kube-eventer/pull/194

**Comment by czhfe** [comment]
> @czhfe 可以参考这个PR重新配置下eventer的yaml。
> #194

好的，这应该是换了个镜像吧，其它的应该没太大问题

**Comment by NUCsimple** [comment]
挂载了一个配置权限的token @czhfe

**Comment by czhfe** [comment]
> 挂载了一个配置权限的token @czhfe

我还是用的master分支的那个例子，然后换了镜像，换成你上面提到的registry-vpc.cn-shanghai.aliyuncs.com/acs/kube-eventer-amd64:v1.2.4-0f5aaee-aliyun 镜像，那这应该是之前代码遗留的问题

**Comment by NUCsimple** [comment]
OK

**Comment by NUCsimple** [comment]
@czhfe 没问题的话，这个issue就先close了。

**Comment by czhfe** [comment]
> @czhfe 没问题的话，这个issue就先close了。

OK

**Comment by NUCsimple** [comment]
@ringtail FYI

**Comment by czhfe** [comment]
@NUCsimple 大佬，上面还有一个问题，就是使用本地虚机自建集群，会出现网络不通的情况，访问到阿里去私网去了，internal参数已经设置了false

**Comment by czhfe** [comment]
> @czhfe 可以发我下完整的sink吗？

sls:https://sls.aliyuncs.com?project=k8slogs-test&logStore=k8s-event-test&topic=huis-test&internal=false

另外AccessKeyId、AccessKeySecret和RegionId是通过Deployment部署模板的env进行配置

**Comment by NUCsimple** [comment]
@czhfe 看起来配置没有问题，虚机网络正常吗？

**Comment by czhfe** [comment]
> @czhfe 看起来配置没有问题，虚机网络正常吗？

虚拟机网络是正常的，能访问到公网，但不知道为什么，kube-eventer走的阿里云内网地址访问sls了，我已经把internal设置了false，但不起作用

**Comment by NUCsimple** [comment]
是用的registry.aliyuncs.com/acs/kube-eventer-amd64:v1.2.0-484d9cd-aliyun这个镜像还是？ @czhfe

**Comment by czhfe** [comment]
> 是用的registry.aliyuncs.com/acs/kube-eventer-amd64:v1.2.0-484d9cd-aliyun这个镜像还是？ @czhfe

registry.aliyuncs.com/acs/kube-eventer-amd64:v1.2.0-484d9cd-aliyun和registry.aliyuncs.com/acs/kube-eventer-amd64:v1.2.4-0f5aaee-aliyun 都测试过，都存在这个问题

**Comment by NUCsimple** [comment]
@czhfe 已经找到问题所在，近期我们修复下

**Comment by czhfe** [comment]
> @czhfe 已经找到问题所在，近期我们修复下

好的

**Comment by NUCsimple** [comment]
@czhfe 可以用1314520999/kube-eventer:v1.2.0-d169962-aliyun试下，我这边用这个测试是OK的
