### ISSUE TITLE
我想添加一个markdown富文本格式的钉钉推送

### ISSUE THREAD

**Issue by zeusro** [AliyunContainerService/kube-eventer#2]
## 现状

目前钉钉推送的格式类似是这样的
```
<clusterid>
Level:Warning 
Namespace:default 
Name:pod-abcd
Message:Port 31666 was assigned to multiple services; please recreate service 
Reason:PortAlreadyAllocated 
Timestamp:3019-07-01 08:38:03 +0000 UTC
```

## [<clusterid>](https://cs.console.aliyun.com/k8s/<clusterid>/#!/overview)
> Level: **Warning**
>
> Namespace: **default**
>
> Name: [pod-abcd](https://cs.console.aliyun.com/#/k8s/deployment/detail/<region>/<clusterid>/default/pod-abcd)
>
> Message: Port 31666 was assigned to multiple services; please recreate service 
>
> Reason:PortAlreadyAllocated 
>
> Timestamp:3019-07-01 08:38:03 +0000 UTC

根据你们控制台的URL规律以及event的事件类型,显示对应的URL

Deployment/Pod

https://cs.console.aliyun.com/#/k8s/deployment/detail/<region>/<clusterid>/default/deployment1/pods

StatefulSet

https://cs.console.aliyun.com/#/k8s/statefulset/detail/<region>/<clusterid>/default/statefulset1/pods

DaemonSet

https://cs.console.aliyun.com/#/k8s/daemonset/detail/<region>/<clusterid>/kube-system/daemonset1/pods

## todo

1. 需要把label预设为集群ID,或者追加一个clusterID参数
1. 需要在容器的启动命令追加参数,传入region和msgtype

[参考链接](https://open-doc.dingtalk.com/microapp/serverapi2/ye8tup#-6)

**Comment by ringtail** [comment]
@zeusro Looking forward to your PR.

**Comment by zeusro** [comment]
@ringtail  https://github.com/AliyunContainerService/kube-eventer/pull/6

**Comment by ringtail** [comment]
Merged to Master
