### ISSUE TITLE
钉钉相同消息重复推送

### ISSUE THREAD

**Issue by DancingCorp** [AliyunContainerService/kube-eventer#20]
是否可以让同一条Warning信息,钉钉不要重复推送.

**Comment by ringtail** [comment]
一般是backoff机制造成的，重试的时候会再次发出异常的信息。对于当个对象进行event聚合是可行的，对局全局而言，会比较消耗性能与空间，目前应该不会支持，如果有更好的办法，我们可以讨论。

**Comment by DancingCorp** [comment]
我们这边观察到,比如一个pod发生了6次backoff,但是钉钉推送了25次,实际使用中,钉钉推送的次数,都远大于get events看到的Warning条数

**Comment by DancingCorp** [comment]
现在我们看到Unhealthy和backoff发生时,都是推送次数是异常的信息的好几倍,如果是每次重试推一次,其实也是可以的,毕竟如果一直在重试还是需要一直进行通知的.

**Comment by ringtail** [comment]
@DancingCorp 当出现问题的时候，事件是完全重复的吗，还是有些许的差异，例如时间戳，UUID或者Ref等等。

**Comment by DancingCorp** [comment]
我这边看到钉钉推送的Timestamp 是相同的,重复推送的那几条,应该是对应同一个event,但是不是100%会发生,这种情况

**Comment by DancingCorp** [comment]
不好意思,重新确认了一下,是一个POD的多个副本集,在同一个时刻出现异常,我们认为是重复推送了,重新核对了最近几天的重复记录后,看到是不同的副本集出现的.
