### ISSUE TITLE
怎么验证采集到的事件到ES是否有丢失啊

### ISSUE THREAD

**Issue by SupRenekton** [AliyunContainerService/kube-eventer#203]
kube-eventer是revision机制，可以考虑在revision处增加相关的trace-id到event，这样可以通过Event上面trace-id的连续性来判断事件是否有丢失。

**Comment by ringtail** [comment]
可以考虑增加Event的ID，根据ID的连续性判断，但是这里的问题在于k8s对event也不是完全保活。
