### ISSUE TITLE
事件信息漏采

### ISSUE THREAD

**Issue by huangleilz** [AliyunContainerService/kube-eventer#208]
pod寻找不到合适得pvc绑定事件采集不到。
![image](https://user-images.githubusercontent.com/42317174/139365825-93d30d6e-adad-4159-a1ef-4423c381dca4.png)

**Comment by ringtail** [comment]
可以get event看下详情，默认采集的逻辑不区分事件内容。

**Comment by KeyOfSpectator** [comment]
请尝试升级最新的kube-eventer版本，如1.2.7以上，此类问题怀疑是老kube-eventer的apiVersion适配不了新版本的集群。
