### ISSUE TITLE
dingtalk群二维码失效

### ISSUE THREAD

**Issue by cuiyuanrong** [AliyunContainerService/kube-eventer#210]
想加群交流，二维码失效，求新的二维码。

**Comment by CN-Eden** [comment]
同求

**Comment by ringtail** [comment]
已更新

**Comment by wanggithub08** [comment]
群限制人数了

**Comment by ringtail** [comment]
> 群限制人数了

目前应该没有限制，可以再试下。

**Comment by wanggithub08** [comment]
扫码添加依然提示，“你所在组织的管理员限制了群人数，无法添加新成员”。在 2022年11月28日，10:55，ringtail ***@***.***> 写道：﻿

群限制人数了

目前应该没有限制，可以再试下。

**Comment by ringtail** [comment]
> 你所在组织的管理员限制了群人数，无法添加新成员”。在 2022年11月28日，10:55，ringtail ***@***.***> 写道：

开启了

**Comment by KeyOfSpectator** [comment]
重启拉了2群
钉钉一群（加不进人了）
群号 30612594
钉钉二群 
群号 5605020816
