### ISSUE TITLE
如何区分集群

### ISSUE THREAD

**Issue by dkaiyun** [AliyunContainerService/kube-eventer#213]
用飞书v2的webhook 在sink中添加了label后  收到的信息中不包含label
![image](https://user-images.githubusercontent.com/46917564/146143246-fa176e31-d363-4cf3-be2e-50ad67458e39.png)
![image](https://user-images.githubusercontent.com/46917564/146143289-0c15fdcf-5357-471d-bd64-768ffebf1d99.png)

**Comment by ringtail** [comment]
可以通过webhook的模型，使用label进行区分
