### ISSUE TITLE
只将里面的client-go升级，不动代码后会影响到kube-eventer功能么

### ISSUE THREAD

**Issue by SupRenekton** [AliyunContainerService/kube-eventer#215]
go get: upgraded github.com/golang/protobuf v1.3.2 => v1.5.2
go get: upgraded github.com/google/uuid v1.1.1 => v1.1.2
go get: upgraded github.com/stretchr/testify v1.6.1 => v1.7.0
go get: upgraded k8s.io/api v0.17.4 => v0.23.1
go get: upgraded k8s.io/apimachinery v0.17.4 => v0.23.1
go get: upgraded k8s.io/client-go v0.17.4 => v0.23.1

**Comment by ringtail** [comment]
大部分场景不会，除非有version的变化。
