### ISSUE TITLE
使用消息模式替换基于定时器的数据处理

### ISSUE THREAD

**Issue by wangzhipeng** [AliyunContainerService/kube-eventer#218]
大框架采用的是timer的方式进行的数据处理的触发，在事件源的处理上采用的消息推送，是否考虑整体都采用推模式，更加符合k8s整体的消息架构，另外多处的timer存在泄露，可以采用NewTicker

**Comment by ringtail** [comment]
> 大框架采用的是timer的方式进行的数据处理的触发，在事件源的处理上采用的消息推送，是否考虑整体都采用推模式，更加符合k8s整体的消息架构，另外多处的timer存在泄露，可以采用NewTicker

这个策略是一个不错的思路，目前主要的逻辑是为了实现的简单。
