### ISSUE TITLE
支持tls吗？输出到ES报错

### ISSUE THREAD

**Issue by PungYoung** [AliyunContainerService/kube-eventer#227]
kubectl logs -f kube-eventer-77cf6fd954-7vnnd -n kube-system

false nodes=http://elasticsearch-es-http.default.svc.cluster.local:9200?sniff=false&ver=7&esUserName=elastic&esUserSecret=0991gEn3bY48m5hRCF8YwyK2 }} sink: Failed to create ElasticSearch client: failed to an ElasticSearch Client: health check timeout: Head "http://elasticsearch-es-http.default.svc.cluster.local:9200": EOF: no Elasticsearch node available

配置：
 - --sink=elasticsearch:?nodes=https://elasticsearch-es-http.default.svc.cluster.local:9200?sniff=false&ver=7&esUserName=elastic&esUserSecret=0991gEn3bY48m5hRCF8YwyK2

**Comment by ringtail** [comment]
tls的证书是私签的吗

**Comment by zhuhao22** [comment]
我也是刚刚配的tls，报错是unkown authenticate....
event yaml文件里需要加secret吗
配置：
--sink=elasticsearch:https://security-master:9200?sniff=false&ver=7&esUserName=elastic&esUserSecret=xxxxxxxxxxxxxxxx
