### ISSUE TITLE
针对不同的namespace进行报警&自定义条件报警

### ISSUE THREAD

**Issue by pioneerli** [AliyunContainerService/kube-eventer#24]
背景
1.需要针对不通namespace的报警，比如pro namespace报警到指定群，uat namespace报警到指定群
2.可不可以支持自定义条件报警，比如说只报ErrImagePull的错误信息到指定群

**Comment by ringtail** [comment]
@pioneerli 事件级别的报警或许过细了，同类型多Sink是可以计划支持的。

**Comment by ringtail** [comment]
@pioneerli Link to #94

**Comment by ringtail** [comment]
可以配置多个同类型Sink，过滤在最新的泛化webhook中支持了
