### ISSUE TITLE
elastic上做了nginx反代理，kube-eventer传输时失败居多，nginx边要增加什么参数啊

### ISSUE THREAD

**Issue by zhuhao22** [AliyunContainerService/kube-eventer#245]
nginx反向代理同时开了密码验证
日志报错
# kubectl logs -f  kube-eventer-79bbdc684c-8mpkh -nelk 
I0804 14:30:41.054241       1 eventer.go:67] /kube-eventer --source=kubernetes:https://kubernetes.default --sink=elasticsearch:http://<ip>:<port>?sniff=false&esUserName=es&esUserSecret=elastic123&ver=7&index=myevent
I0804 14:30:41.054426       1 eventer.go:68] kube-eventer version: v1.2.0 commit: 484d9cd
I0804 14:30:41.071193       1 eventer.go:94] Starting with ElasticSearch Sink sink
I0804 14:30:41.071272       1 eventer.go:108] Starting eventer
I0804 14:30:41.071315       1 eventer.go:116] Starting eventer http service
I0804 14:31:00.000261       1 manager.go:102] Exporting 39 events
I0804 14:31:30.000309       1 manager.go:102] Exporting 153 events
W0804 14:31:50.000797       1 manager.go:108] Failed to events data to sink: ElasticSearch Sink
I0804 14:32:00.000368       1 manager.go:102] Exporting 36 events
W0804 14:32:20.000842       1 manager.go:108] Failed to events data to sink: ElasticSearch Sink
I0804 14:32:30.000457       1 manager.go:102] Exporting 41 events
W0804 14:32:50.001048       1 manager.go:108] Failed to events data to sink: ElasticSearch Sink
I0804 14:33:00.000499       1 manager.go:102] Exporting 57 events
W0804 14:33:20.001026       1 manager.go:108] Failed to events data to sink: ElasticSearch Sink
I0804 14:33:30.000599       1 manager.go:102] Exporting 24 events
W0804 14:33:50.001064       1 manager.go:108] Failed to events data to sink: ElasticSearch Sink
I0804 14:34:00.000468       1 manager.go:102] Exporting 22 events
W0804 14:34:20.000888       1 manager.go:108] Failed to events data to sink: ElasticSearch Sink
I0804 14:34:30.000341       1 manager.go:102] Exporting 25 events
W0804 14:34:50.000965       1 manager.go:108] Failed to events data to sink: ElasticSearch Sink
I0804 14:35:00.000405       1 manager.go:102] Exporting 56 events
W0804 14:35:20.000755       1 manager.go:108] Failed to events data to sink: ElasticSearch Sink
I0804 14:35:30.000530       1 manager.go:102] Exporting 21 events
W0804 14:35:50.000938       1 manager.go:108] Failed to events data to sink: ElasticSearch Sink
I0804 14:36:00.000359       1 manager.go:102] Exporting 62 events
W0804 14:36:20.000751       1 manager.go:108] Failed to events data to sink: ElasticSearch Sink
I0804 14:36:30.000337       1 manager.go:102] Exporting 63 events
I0804 14:37:00.000330       1 manager.go:102] Exporting 23 events
I0804 14:37:30.000339       1 manager.go:102] Exporting 131 events

**Comment by KeyOfSpectator** [comment]
麻烦提供更多kube-eventer和es的反向代理配置详情

**Comment by zhuhao22** [comment]
已经放弃这种方式了

---- 回复的原邮件 ----
| 发件人 | Shichun ***@***.***> |
| 发送日期 | 2023年08月28日 17:00 |
| 收件人 | AliyunContainerService/kube-eventer ***@***.***> |
| 抄送人 | zhuhao22 ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [AliyunContainerService/kube-eventer] elastic上做了nginx反代理，kube-eventer传输时失败居多，nginx边要增加什么参数啊 (Issue #245) |

麻烦提供更多kube-eventer和es的反向代理配置详情
