### ISSUE TITLE
建议新增 filters

### ISSUE THREAD

**Issue by myselfghost** [AliyunContainerService/kube-eventer#246]
目前filters 没有包括 Message 正文和 name 的匹配，建议新增这2个filters类型。

**Comment by ringtail** [comment]
目前filters不是全局的，是下沉在sink粒度的，是希望那个sink来支持。

**Comment by KeyOfSpectator** [comment]
如SLS等Sink，支持event labelSelector作为filter。

**Comment by KeyOfSpectator** [comment]
#274
