### ISSUE TITLE
我们想把eventer打到elasticsearch，但是出现了问题

### ISSUE THREAD

**Issue by JennyLJY** [AliyunContainerService/kube-eventer#25]
目前我们使用的是elasticsearch6，配完以后，日志发送的时候报错说不支持string。

W0813 03:37:00.073560       1 driver.go:90] Failed to export data to ElasticSearch sink: elastic: Error 400 (Bad Request): Failed to parse mapping [general]: No handler for type [string] declared on field [cluster_name] [type=mapper_parsing_exception]

**Comment by ringtail** [comment]
麻烦贴下elasticsearch的小版本

**Comment by jiazhiguang** [comment]
> 目前我们使用的是elasticsearch6，配完以后，日志发送的时候报错说不支持string。
> 
> W0813 03:37:00.073560 1 driver.go:90] Failed to export data to ElasticSearch sink: elastic: Error 400 (Bad Request): Failed to parse mapping [general]: No handler for type [string] declared on field [cluster_name] [type=mapper_parsing_exception]

请帖一下启动命令

**Comment by JennyLJY** [comment]
我们是用这个参数的，是不是哪里写错啦
- --sink=elasticsearch:http://es-cn-参数省略.public.elasticsearch.aliyuncs.com:9200?sniff=false&esUserName=用户名省略&esUserSecret=密码省略&cluster_name=集群名字省略

**Comment by JennyLJY** [comment]
> 麻烦贴下elasticsearch的小版本

6.3.2

**Comment by JennyLJY** [comment]
> > 目前我们使用的是elasticsearch6，配完以后，日志发送的时候报错说不支持string。
> > W0813 03:37:00.073560 1 driver.go:90] Failed to export data to ElasticSearch sink: elastic: Error 400 (Bad Request): Failed to parse mapping [general]: No handler for type [string] declared on field [cluster_name] [type=mapper_parsing_exception]
> 
> 请帖一下启动命令

我们是用example里的yaml配的，改了这个参数，配完以后kubectl apply -f 启用的，
参数是不是哪里写错啦？
--sink=elasticsearch:http://es-cn-参数省略.public.elasticsearch.aliyuncs.com:9200?sniff=false&esUserName=用户名省略&esUserSecret=密码省略&cluster_name=集群名字省略

**Comment by ringtail** [comment]
ES 6 does no longer support multiple types in mappings per index. The metrics must be merged to one type or written to different indices.
https://www.elastic.co/guide/en/elasticsearch/reference/6.0/breaking-changes-6.0.html

There is also a new version of the used ES client
https://github.com/olivere/elastic

**Comment by ringtail** [comment]
We may update the ES client version to support es6

**Comment by JennyLJY** [comment]
> ES 6 does no longer support multiple types in mappings per index. The metrics must be merged to one type or written to different indices.
> https://www.elastic.co/guide/en/elasticsearch/reference/6.0/breaking-changes-6.0.html
> 
> There is also a new version of the used ES client
> https://github.com/olivere/elastic

Thank you
