### ISSUE TITLE
pod调度失败的时候时间展示有问题

### ISSUE THREAD

**Issue by wanggithub08** [AliyunContainerService/kube-eventer#253]
使用webhok接入的时候，pod调度失败场景下FirstTimestamp和LastTimestamp这两个字段展示的时间都是下面这样，其他情况是正常的：
FirstTime:0001-01-01 00:00:00 +0000 UTC
LastTime:0001-01-01 00:00:00 +0000 UTC

**Comment by ringtail** [comment]
@wanggithub08 看下k8s集群内的时间，get event的方式获取下，可能原始时间就是有问题的

**Comment by KeyOfSpectator** [comment]
此问题已经修复。#168

**Comment by KeyOfSpectator** [comment]
部分sink已修复，全量sink修复中。

**Comment by KeyOfSpectator** [comment]
#276
