### ISSUE TITLE
kube-eventer 推送到elasticSearch 索引文件名创建时间不在0点创建，有的是在北京时间8:04分，有的是在8:54 

### ISSUE THREAD

**Issue by sincosab** [AliyunContainerService/kube-eventer#254]
我们有台机器的数据总是北京时间8点以前的数据在前一天的索引文件上，不知道是什么原因，我们时区设置都是北京时间，文件里面数据也是对的，不知道是什么原因。请问索引文件是什么时间创建的，谢谢。

**Comment by KeyOfSpectator** [comment]
ES的index，是由kube-eventer Pod启动初始化时进行创建，默认value是heapster，可以通过--sink参数中，添加 index=xxx 进行定义
