### ISSUE TITLE
--source= 如何使用本地kubeconfig？

### ISSUE THREAD

**Issue by zgfh** [AliyunContainerService/kube-eventer#26]
本地调试时，如何配置--source= 使用本地kubeconfig？

**Comment by ringtail** [comment]
可以Follow标准k8s项目的规范，先设置通过`kubectl proxy --port=8080`进行转发代理，然后配置启动参数：`--source=kubernetes:http://127.0.0.1:8080?inClusterConfig=false`，最后配置环境变量`KUBERNETES_SERVICE_HOST=127.0.0.1`与`KUBERNETES_SERVICE_PORT=8080`

**Comment by zgfh** [comment]
感谢，是否应该加个文档？

**Comment by ringtail** [comment]
> 感谢，是否应该加个文档？

https://github.com/AliyunContainerService/kube-eventer/blob/master/docs/en/configuration.md
