### ISSUE TITLE
钉钉推送失败

### ISSUE THREAD

**Issue by bigdimple** [AliyunContainerService/kube-eventer#33]
测试了一下，当level=Warning时，就无法推送消息出来，等于level=Normal时才能正常报警。
环境：本地自建集群
格式：--sink=dingtalk:https://oapi.dingtalk.com/robot/send?access_token=xxxx&label=online-cluster&level=Warning

**Comment by ringtail** [comment]
@bigdimple 确定是存在Warning事件的吗

**Comment by ringtail** [comment]
@bigdimple 有更新的内容和信息吗

**Comment by bigdimple** [comment]
> @bigdimple 有更新的内容和信息吗
不好意思，这么晚才回复

**Comment by dotbalo** [comment]
@ringtail 您好，

我是自己的k8s集群，然后配置的level是normal，eventer的日志如下：
````
I0113 15:40:00.000273       1 manager.go:102] Exporting 7 events
I0113 15:40:30.000207       1 manager.go:102] Exporting 19 events
I0113 15:41:00.000264       1 manager.go:102] Exporting 7 events
I0113 15:41:30.000387       1 manager.go:102] Exporting 20 events
I0113 15:42:00.000233       1 manager.go:102] Exporting 6 events
I0113 15:42:30.000262       1 manager.go:102] Exporting 28 events
````

然后我的钉钉配置如下：
![image](https://user-images.githubusercontent.com/25141522/72239295-844ee000-361b-11ea-963b-2d9d763e2bc5.png)

但是我不能收到钉钉的消息推送呢？能否看下怎么回事？
