### ISSUE TITLE
输出到ES报错

### ISSUE THREAD

**Issue by ArvinChen1991** [AliyunContainerService/kube-eventer#34]
W0904 05:46:30.011489       1 driver.go:90] Failed to export data to ElasticSearch sink: elastic: Error 400 (Bad Request): Failed to parse mapping [general]: No handler for type [string] declared on field [cluster_name] [type=mapper_parsing_exception]

**Comment by ringtail** [comment]
#25

**Comment by ringtail** [comment]
建议到SLS或者钉钉，ES的版本之间存在兼容问题，目前eventer还没有支持到es6

**Comment by ringtail** [comment]
@ArvinChen1991 新的版本已经merge，可以尝试下

**Comment by rralcala** [comment]
let me know if you it worked for you / 让我知道您是否成功

**Comment by ringtail** [comment]
I think this issue could be closed. If need any help, pls reopen it.

**Comment by ZP-AlwaysWin** [comment]
hi @ringtail What is the image ID of the new version ？
My es version is v6.3.0,but still get a error

```
Failed to export data to ElasticSearch sink: elastic: Error 400 (Bad Request): Failed to parse mapping [general]: No handler for type [string] declared on field [cluster_name] [type=mapper_parsing_exception]
```

**Comment by ringtail** [comment]
@ZP-AlwaysWin Pls provide the image you use and sink params.

**Comment by ZP-AlwaysWin** [comment]
# elasticsearch version

```
sh-4.2# curl -XGET localhost:9200
{
  "name" : "elasticsearch-logging-0",
  "cluster_name" : "kubernetes-logging",
  "version" : {
    "number" : "6.3.2",
    "build_flavor" : "oss",
    "build_type" : "tar",
    "build_hash" : "053779d",
    "build_date" : "2018-07-20T05:20:23.451332Z",
    "build_snapshot" : false,
    "lucene_version" : "7.3.1",
    "minimum_wire_compatibility_version" : "5.6.0",
    "minimum_index_compatibility_version" : "5.0.0"
  },
  "tagline" : "You Know, for Search"
}
```

# sink params

```
command:
            - "/kube-eventer"
            - "--source=kubernetes:https://kubernetes.default"
            ## .e.g,dingtalk sink demo
            - "--sink=elasticsearch:http://172.16.44.65:9200?sniff=false"
```

# error info

```
I1101 03:52:30.000236       1 manager.go:102] Exporting 1 events
W1101 03:52:30.067217       1 driver.go:94] Failed to export data to ElasticSearch sink: elastic: Error 400 (Bad Request): Failed to parse mapping [general]: No handler for type [string] declared on field [cluster_name] [type=mapper_parsing_exception]
```

**Comment by ZP-AlwaysWin** [comment]
There is another problem. Can kube-eventer directly save the collected events to the local file now？

**Comment by ringtail** [comment]
@ZP-AlwaysWin what's the image tag you used.

**Comment by ZP-AlwaysWin** [comment]
> @ZP-AlwaysWin what's the image tag you used.

image: registry.aliyuncs.com/acs/kube-eventer-amd64:v1.1.0-63e7f98-aliyun

**Comment by ringtail** [comment]
> There is another problem. Can kube-eventer directly save the collected events to the local file now？

There is no local file sink for now. Welcome to submit a pr.

**Comment by ringtail** [comment]
@NUCsimple Pls check this issue.

**Comment by ZP-AlwaysWin** [comment]
> > There is another problem. Can kube-eventer directly save the collected events to the local file now？
> 
> There is no local file sink for now. Welcome to submit a pr.

oo,Thanks， I will try，I just think temporary use, convenient to store locally.

**Comment by ringtail** [comment]
> > > There is another problem. Can kube-eventer directly save the collected events to the local file now？
> > 
> > 
> > There is no local file sink for now. Welcome to submit a pr.
> 
> oo,Thanks， I will try，I just think temporary use, convenient to store locally.

We support to log to kube-eventer pod's stdout. But it's usually used for debugging.

**Comment by NUCsimple** [comment]
> 嗨@ringtail新版本的图像ID是什么？
> 我的es版本是v6.3.0，但仍然出现错误
> 
> ```
> Failed to export data to ElasticSearch sink: elastic: Error 400 (Bad Request): Failed to parse mapping [general]: No handler for type [string] declared on field [cluster_name] [type=mapper_parsing_exception]
> ```



> hi @ringtail What is the image ID of the new version ？
> My es version is v6.3.0,but still get a error
> 
> ```
> Failed to export data to ElasticSearch sink: elastic: Error 400 (Bad Request): Failed to parse mapping [general]: No handler for type [string] declared on field [cluster_name] [type=mapper_parsing_exception]
> ```

pls add version tag in your sink link;like this:--sink=elasticsearch:http://127.0.0.1:9200?sniff=false&ver=6

**Comment by ringtail** [comment]
@NUCsimple Pls update the docs and add attention notice about it.

**Comment by NUCsimple** [comment]
> @NUCsimple Pls update the docs and add attention notice about it.
OK
