### ISSUE TITLE
/metrics不能使用

### ISSUE THREAD

**Issue by yehaifeng** [AliyunContainerService/kube-eventer#35]
启动kube-eventer之后启动了一个8084端口，但是/metrics报404错误。

/ $ wget http://10.128.14.53:8084/metrics/
Connecting to 10.128.14.53:8084 (10.128.14.53:8084)
wget: server returned error: HTTP/1.1 404 Not Found

**Comment by ringtail** [comment]
@yehaifeng 暂时还没有支持/metrics，你期望暴露什么metrics

**Comment by DeepLJH0001** [comment]
直接把event吐到metrics上面，普罗对接过去做历史事件持久化，类似才云的那个event_exporter

**Comment by ringtail** [comment]
event的量级比较大，拉取的模式很难适配
