### ISSUE TITLE
ES Parameter problem

### ISSUE THREAD

**Issue by NUCsimple** [AliyunContainerService/kube-eventer#39]
When using es as the event receiver, When you specify the sink parameter, if you do not set use_namespace,The following error will be displayed:
`W1010 03:22:00.006045       1 driver.go:94] Failed to export data to ElasticSearch sink: elastic: Error 400 (Bad Request): Invalid index name [heapster-2019-10-10 07:21:55
+0000 UTC], must not contain the following characters [ , ", *, \, <, |, ,, >, /, ?] [type=invalid_index_name_exception]`
So,if this parameter must be specified, please help to join the es help file. @rralcala @ringtail

**Comment by rralcala** [comment]
I think I know the problem, I can take a look.

**Comment by NUCsimple** [comment]
OK,thanks
