### ISSUE TITLE
支持微信和邮件吗

### ISSUE THREAD

**Issue by fyqls** [AliyunContainerService/kube-eventer#4]

**Comment by ringtail** [comment]
@fyqls 微信暂未支持，邮件可能不会支持，数据量比较大的时候不合适，如果有兴趣可以提交PR

**Comment by fyqls** [comment]
后面对接promethues，有没有好的建议．

**Comment by ringtail** [comment]
> 后面对接promethues，有没有好的建议．

eventer和prometheus不是不可以结合，只是结合后的效果可能只剩下存储集成了，短时间我们可能先不会考虑到prometheus。

**Comment by ringtail** [comment]
#23

**Comment by ringtail** [comment]
微信的sink已经有人提交了，还在review修改中。
