### ISSUE TITLE
逻辑上的误报 和 告警频繁问题，求助。

### ISSUE THREAD

**Issue by G-master** [AliyunContainerService/kube-eventer#42]
试用了一段时间，    发现   在更新 Deployment 的时候   Pod伸缩的时候 ， 也会 报警，    只要 Pod的状态 改变都会触发 报警，       能不能 判断一下，     区分下 是意料之中的状态改变， 还是 应该 报警的状态。 

是否能延迟报警，   将 状态改变的Pod  放入待观察的队列里， 进行进一步的赛选呢。

太过频繁的报警 让我们 无法区分 到底 要不要去处理

**Comment by ringtail** [comment]
设置报警Level为Warning

**Comment by ist0ne** [comment]
设置成Warning并不能解决上述问题，最好能够实现事件的汇总发送，否则大量状态变更（比如Pod大规模更新）时产生警报风暴。

**Comment by G-master** [comment]
是的，现在的报警级别 就是  warning   ，因为警报风暴 和警报的 参考价值不高..  停用了这个 组件。

**Comment by ringtail** [comment]
@G-master 可以考虑离线到SLS，然后使用关键字告警。

**Comment by ringtail** [comment]
@G-master #43 是否满足需求

**Comment by G-master** [comment]
@ringtail   

warning 报警 并非是 不准确的，   通过关键字筛选， 并不能解决这个问题，    warning的报警信息我们也是需要的，  但是现在触发它的条件 是多样的， （更新  ，重启 和 启动失败 ）  ，是否可以配合其他的条件   去触发这个操作，  比如  5m内  仍然没有恢复，  或者   重启次数一直在增加。 


合并通refer的报警事件是否满足需//   抱歉 这里没有理解您的意思。

**Comment by ringtail** [comment]
@G-master 大致的意思就是，Pod的Refer Deployment一致是，Event做合并。

**Comment by zeusro** [comment]
这个问题我也遇过。更新deployment 的时候
1.  内部健康检查老是warning ，提示 Readiness probe failed /connect: connection refused
2. sidecar container 提示 FailedPreStopHook 

我觉得 https://github.com/AliyunContainerService/kube-eventer/issues/43 并不能从根本上解决问题。

但kubernetes 1.18 也许能一定程度上缓解这个问题
https://cloud.tencent.com/developer/article/1585439

**Comment by zhangshunping** [comment]
我配置的钉钉告警如下： - --sink=dingtalk:https://oapi.dingtalk.com/robot/send?access_token=******&level=Warning&namespaces=kube-system,default&label=Pre-k8s&kinds=Pod
报警的类型满足我的需求，但是发现一条message要重复发送25次，请问这个有什么好的办法吗？

**Comment by ringtail** [comment]
麻烦截个图，看下是否是不同的Pod产生的

**Comment by mozillazg** [comment]
依我愚见，这个项目可能只定位为一个事件数据输出源会更好一点，把事件数据输出到各个外部系统，让那些系统来实现复杂的业务需求（比如监控、告警、报表分析等等），至于那些数据去重、聚合之类的操作可以由外部数据处理系统自己来实现：

```
kube-eventer (events) --> external system -> storage -> analysis -> report -> alarm
```

**Comment by ringtail** [comment]
> 依我愚见，这个项目可能只定位为一个事件数据输出源会更好一点，把事件数据输出到各个外部系统，让那些系统来实现复杂的业务需求（比如监控、告警、报表分析等等），至于那些数据去重、聚合之类的操作可以由外部数据处理系统自己来实现：
> 
> ```
> kube-eventer (events) --> external system -> storage -> analysis -> report -> alarm
> ```

恩恩，SLS的场景是可以解决上面问题的，不过钉钉chatops能力优化是要进行的。

**Comment by mozillazg** [comment]
钉钉chatops能力优化 可以考虑新创建一个单独的项目来实现，把这个 chatops 项目在集群内部署为 一个 service ，这样即可以保持 kube-eventer  项目的纯粹性又可以实现 钉钉chatops 的复杂定制化需求:

```
kube-eventer (events) -> dingtalk chatops service(aggregate、format、filter etc.) -> dingtalk webhook

```

**Comment by ringtail** [comment]
> 钉钉chatops能力优化 可以考虑新创建一个单独的项目来实现，把这个 chatops 项目在集群内部署为 一个 service ，这样即可以保持 kube-eventer 项目的纯粹性又可以实现 钉钉chatops 的复杂定制化需求:
> 
> ```
> kube-eventer (events) -> dingtalk chatops service(aggregate、format、filter etc.) -> dingtalk webhook
> ```
是否过于复杂了
