### ISSUE TITLE
能不能添加基于Reason的报警过滤规则？

### ISSUE THREAD

**Issue by ist0ne** [AliyunContainerService/kube-eventer#44]
有些Warning报警确认是不影响实际使用的，且一段时间内无法消除掉，所有需要一个基于Reason的报警过滤规则

**Comment by ringtail** [comment]
能否举几个例子，哪些的warning希望消除，另外reson过滤希望的方式是什么样子的。

**Comment by ist0ne** [comment]
@ringtail 可以实现一个排查列表，类似于Namespaces参数，比如：exReasons: DNSConfigForming,Unhealthy

**Comment by ringtail** [comment]
这个event是coredns发出的吗

**Comment by ringtail** [comment]
@BSWANG 麻烦看下这个是否是coredns的问题，以及社区是否有修复方案。

**Comment by ist0ne** [comment]
@ringtail 我只是举个例子，这个问题很好修复，把宿主机的/etc/resolv.conf配置成3个nameserver，并重启kubelet就可以解决。问题是要能够排查不想接收的事件，比如Unhealthy的事件。

**Comment by ringtail** [comment]
明白，我在想直接reason过滤会对钉钉告警显得过重，是否使用sls+关键字告警会更合适。

**Comment by ringtail** [comment]
@ist0ne 是钉钉Sink吗

**Comment by ringtail** [comment]
Link to #94
