### ISSUE TITLE
支持私有化环境的k8s集群么

### ISSUE THREAD

**Issue by imdingtalk** [AliyunContainerService/kube-eventer#5]
配置文件中的   label=[your_cluster_id]    这个 your_cluster_id的值 是阿里云的环境中才有的么。可以使用该项目用于自己私有化环境搭建的k8s集群么

**Comment by ringtail** [comment]
> 配置文件中的 label=[your_cluster_id] 这个 your_cluster_id的值 是阿里云的环境中才有的么。可以使用该项目用于自己私有化环境搭建的k8s集群么

可以使用，这个cluster_id可以是任何东西，这个地方只是拒了一个例子
