### ISSUE TITLE
钉钉发送失败

### ISSUE THREAD

**Issue by m198799** [AliyunContainerService/kube-eventer#52]
钉钉发送使用加签模式下
出现错误

I1220 16:46:20.997661       1 eventer.go:67] /kube-eventer --source=kubernetes:https://kubernetes.default --sink=dingtalk:https://oapi.dingtalk.com/robot/send?access_token=xxxxxxxx&timestamp=1576831364338&sign=qBQH5DbKEs8NMyrpNZ%!B(MISSING)Id6Tp%!F(MISSING)MW4eYPAkWWS8O2RZSc%!D(MISSING)&label=c453bfb4987314ca9b31e5ed3c188aa2a&level=Normal

**Comment by m198799** [comment]
![image](https://user-images.githubusercontent.com/3634397/71243694-d4ec5980-234b-11ea-91a2-71c265320920.png)

生成标签后写入yaml，通过kubectl create yaml 文件内sign和生成不一直。

**Comment by ringtail** [comment]
sign是什么

**Comment by m198799** [comment]
![image](https://user-images.githubusercontent.com/3634397/71347910-593a1900-25a6-11ea-8ee7-a83079b1128f.png)
钉钉安全设置里支持3个模式
自定义字段，加签，ip。
sign就是 加签
https://ding-doc.dingtalk.com/doc#/serverapi2/qf2nxq

**Comment by ringtail** [comment]
是增加了钉钉机器人的安全设置是吗？这块可以先去掉，默认没有做这个的实现，我们需要自己做下测试。

**Comment by m198799** [comment]
好的感谢

**Comment by ringtail** [comment]
我记录一个issue，看下这个feature

**Comment by zeusro** [comment]
@m198799  这块功能初版是我开发的。我当时写那部分代码的时候，钉钉这部分功能还没出。
感兴趣的话，你可以看看
[dingtalk](https://github.com/AliyunContainerService/kube-eventer/tree/master/sinks/dingtalk)
这里，整个处理的逻辑无非就是从启动参数里面解析读取参数，传入到对应的 sinks 去处理。不是很难，只是要花点时间。
