### ISSUE TITLE
建议增加新的sink，支持自定义webhook

### ISSUE THREAD

**Issue by runningbeanxl** [AliyunContainerService/kube-eventer#54]
希望能支持自定义的webhook机器人

**Comment by ringtail** [comment]
是否有预期接入的系统，还是期望由kube-eventer定义接口规范。

**Comment by runningbeanxl** [comment]
预期接入倍洽

**Comment by zeusro** [comment]
@ringtail 感觉可以开个 钉钉用户群组

**Comment by ringtail** [comment]
> @ringtail 感觉可以开个 钉钉用户群组

你来组织吧 @zeusro

**Comment by ringtail** [comment]
BearChat、Slack、钉钉是类似的，应该抽离成统一的组件，@mozillazg 是否统一抽一下。

**Comment by mozillazg** [comment]
其实差异蛮大的（核心的消息数据格式每家都不一样，可能还会有各种各样的个性化需求），共性只有一个，那就是都是发送 http 请求。

我个人其实比较倾向于作为核心的 kube-eventer 不要包含太多业务相关的功能，只做核心功能，sink 里的业务逻辑如果比较复杂的话，建议通过独立的服务来实现（比如钉钉通知，这个其实个性化的需求特别多，如果有个性化需求的话建议通过独立的服务来实现，而不是在 kube-eventer 里做复杂的适配），然后通过 webhook sink 来串联 kube-eventer 和实现了个性化需求的消息接收服务。原因是：kube-eventer 服务应当保持长久运行以保证事件尽量不遗漏，而不是时不时就需要更新一下，每次更新的时候容易出现事件遗漏，以及不夹杂非核心的功能更容易确保服务的稳定性，bug 相对来说也会更少一点。

**Comment by sunruipu** [comment]
dingtalk的webhook-url可以换成自己开发的webhook。但前提是接口url支持https，因为源码里写死了https:" resp, err := http.Post(fmt.Sprintf("https://%s?access_token=%s", d.Endpoint, d.Token), CONTENT_TYPE_JSON, b)"

**Comment by ringtail** [comment]
@sunruipu Pls check this PR #94

**Comment by ringtail** [comment]
link to #94
