### ISSUE TITLE
部署kube-eventer后，etcd报错增多

### ISSUE THREAD

**Issue by dotbalo** [AliyunContainerService/kube-eventer#55]
您好，经过多次测试，只要部署kube-eventer以后，etcd的报错就增多，关闭后，就正常。请问这个是怎么回事？
![image](https://user-images.githubusercontent.com/25141522/72497381-4cd47380-3867-11ea-9378-a364a067f16d.png)

Prometheus查询语法：
````
sum by(grpc_service, grpc_method) (rate(grpc_server_handled_total{grpc_code!="OK",job="etcd"}[5m])) / sum by(grpc_service, grpc_method) (rate(grpc_server_handled_total{job="etcd"}[5m])) > 0.01
````

**Comment by ringtail** [comment]
可以看下etcd的版本，link to issue(https://github.com/etcd-io/etcd/issues/9166)

**Comment by dotbalo** [comment]
@ringtail 您好，版本如下：
````
[x@k8s-master01 ~]$ etcd --version
etcd Version: 3.3.9
Git SHA: fca8add78
Go Version: go1.10.3
Go OS/Arch: linux/amd64
````

k8s版本:
````
[x@k8s-master01 ~]$ kubelet --version
Kubernetes v1.13.5

````

在没有部署kube-eventer时，etcd没有出现过这个报错，只要部署上，就会出现这个错误。

**Comment by ringtail** [comment]
@NUCsimple  Pls follow this up.
