### ISSUE TITLE
建议增加报警频率设置

### ISSUE THREAD

**Issue by yangmingqi218** [AliyunContainerService/kube-eventer#56]
您好，建议增加报警的频率设置，不然集群内的pod出现问题，不论设置的Warining还是Normal，钉钉上都会连续收到报警，而客户希望一种情况只收到一条报警就好了

**Comment by ringtail** [comment]
可以先把事件Level调整到Warning，另外事件聚合和静默时间的Feature已经在计划中了

**Comment by yangmingqi218** [comment]
好的&nbsp; &nbsp;谢谢您，已经设置了Warning



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "ringtail"<notifications@github.com&gt;; 
发送时间: 2020年1月19日(星期天) 上午10:48
收件人: "AliyunContainerService/kube-eventer"<kube-eventer@noreply.github.com&gt;; 
抄送: "小愤青"<627958623@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [AliyunContainerService/kube-eventer] 建议增加报警频率设置 (#56)




可以先把事件Level调整到Warning，另外事件聚合和静默时间的Feature已经在计划中了
