### ISSUE TITLE
添加钉钉报警这个目前只支持阿里云的k8s吗

### ISSUE THREAD

**Issue by liyin37** [AliyunContainerService/kube-eventer#59]
--sink=dingtalk:[your_webhook_url]&label=[your_cluster_id]&level=[可选参数:Normal或者Warning，默认值为：Warning]
这个代码中的your_cluster_id 只能是阿里云的k8s吗，如果是自己搭建的k8s这个字段如何写

**Comment by ringtail** [comment]
your_cluster_id只是举了一个例子，前面的标签名字是label，这个字段只是为了标识不同集群的信息

**Comment by liyin37** [comment]
意思是：如果是自己搭建的k8s环境，这个label不写就可以了吗

**Comment by ringtail** [comment]
也可以的

**Comment by liyin37** [comment]
我测试了下，使用你的deployment如下：
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kube-eventer
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        task: monitoring
        k8s-app: kube-eventer
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      containers:
      - name: kube-eventer
        image: registry.cn-hangzhou.aliyuncs.com/acs/kube-eventer-amd64:v1.0.0-d9898e1-aliyun
        imagePullPolicy: IfNotPresent
        command:
        - /kube-eventer
        - --source=kubernetes:https://kubernetes.default
        - --sink=dingtalk:[https://oapi.dingtalk.com/robot/send?access_token=4ef7e58a754791229e215d7d16c575016972d4d939xxxxxxxxb1cf9bb35]&level=[Warning]

在k8s中运行报错了
![image](https://user-images.githubusercontent.com/42507175/74639415-d64dcd00-51a8-11ea-802e-0f06cbb36a99.png)
这个如何解决呢，麻烦帮看下，谢谢

**Comment by ringtail** [comment]
去掉[]

**Comment by liyin37** [comment]
如何模拟k8s异常，然后钉钉报警呢，当前我设置了Normal，钉钉没有任何反应

https://oapi.dingtalk.com/robot/send?access_token=4ef7e58a754791229e215d7d16c5750xxxxxxx1ec4cb1cf9bb35&label=huaweik8s&level=Normal

**Comment by ringtail** [comment]
Normal事件可以通过Pod的更新应用之类的方式模拟

**Comment by ringtail** [comment]
另外可以通过https://github.com/ringtail/kubernetes-events-generator 模拟所有k8s事件
