### ISSUE TITLE
使用您提供的yaml示例修改后无法部署到k8s中

### ISSUE THREAD

**Issue by liyin37** [AliyunContainerService/kube-eventer#60]
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    name: kube-eventer
  name: kube-eventer
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-eventer
  template:
    metadata:
      labels:
        app: kube-eventer
      annotations:	
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      serviceAccount: kube-eventer
      containers:
        - image: registry.aliyuncs.com/acs/kube-eventer-amd64:v1.1.0-63e7f98-aliyun
          name: kube-eventer
          command:
            - "/kube-eventer"
            - "--source=kubernetes:https://kubernetes.default"
            ## .e.g,dingtalk sink demo
            - --sink=dingtalk:[your_webhook_url]&label=[your_cluster_id]&level=[Normal or Warning(default)]
          env:
          # If TZ is assigned, set the TZ value as the time zone
          - name: TZ
            value: America/New_York
          volumeMounts:
            - name: localtime
              mountPath: /etc/localtime
              readOnly: true
            - name: zoneinfo
              mountPath: /usr/share/zoneinfo
              readOnly: true
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 500m
              memory: 250Mi
      volumes:
        - name: localtime
          hostPath:
            path: /etc/localtime
        - name: zoneinfo
          hostPath:
            path: /usr/share/zoneinfo
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kube-eventer
rules:
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
  name: kube-eventer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-eventer
subjects:
  - kind: ServiceAccount
    name: kube-eventer
    namespace: kube-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-eventer
  namespace: kube-system

提示报错
![image](https://user-images.githubusercontent.com/42507175/74659023-7ff38500-51ce-11ea-9727-7e4a45f261e5.png)
当前kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:16:51Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.6", GitCommit:"7015f71e75f670eb9e7ebd4b5749639d42e20079", GitTreeState:"clean", BuildDate:"2019-11-13T11:11:50Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}

kubeletes-dashboard版本是：
![image](https://user-images.githubusercontent.com/42507175/74659096-a4e7f800-51ce-11ea-97c3-75f7a6540875.png)

**Comment by liyin37** [comment]
删除权限配置部署上去后，容器中报错是：
![image](https://user-images.githubusercontent.com/42507175/74661912-d57e6080-51d3-11ea-861c-0f187c1982b0.png)

**Comment by ringtail** [comment]
kubernetes的版本麻烦贴一下

**Comment by ringtail** [comment]
另外检查下serviceaccount、clusterrole等哪个资源没有创建成功，看上去是这个k8s的版本有一部分的resource apiversion和yaml中不匹配

**Comment by liyin37** [comment]
root@k8snode-0001:~# kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:16:51Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.6", GitCommit:"7015f71e75f670eb9e7ebd4b5749639d42e20079", GitTreeState:"clean", BuildDate:"2019-11-13T11:11:50Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}

我使用kubectl expain 对比看了下

kubectl get serviceaccount -n kube-system|grep kube 执行是没有数据的

**Comment by liyin37** [comment]
这serviceaccount、clusterrole等几个资源都没有创建起来

**Comment by ringtail** [comment]
看上去是`---`解析出了问题，可以把Yaml拆成几个部分，依次下发

**Comment by liyin37** [comment]
只执行：
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kube-eventer
rules:
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - get
      - list
      - watch
报错
the server could not find the requested resource
![image](https://user-images.githubusercontent.com/42507175/74668762-da95dc80-51e0-11ea-923d-d2fa0a0f37bd.png)

**Comment by liyin37** [comment]
您这个示例是有权限控制的，不设置pod运行后，容器会报错
E0217 15:57:30.163580       1 kubernetes_source.go:110] Failed to load events: events is forbidden: User "system:serviceaccount:kube-system:kube-eventer" cannot list resource "events" in API group "" at the cluster scope
E0217 15:57:31.164409       1 kubernetes_source.go:110] Failed to load events: events is forbidden: User "system:serviceaccount:kube-system:kube-eventer" cannot list resource "events" in API group "" at the cluster scope
E0217 15:57:32.165279       1 kubernetes_source.go:110] Failed to load events: events is forbidden: User "system:serviceaccount:kube-system:kube-eventer" cannot list resource "events" in API group "" at the cluster scope
E0217 15:57:33.166234       1 kubernetes_source.go:110] Failed to load events: events is forbidden: User "system:serviceaccount:kube-system:kube-eventer" cannot list resource "events" in API group "" at the cluster scope
E0217 15:57:34.167014       1 kubernetes_source.go:110] Failed to load events: events is forbidden: User "system:serviceaccount:kube-system:kube-eventer" cannot list resource "events" in API group "" at the cluster scope
E0217 15:57:35.167879       1 kubernetes_source.go:110] Failed to load events: events is forbidden: User "system:serviceaccount:kube-system:kube-eventer" cannot list resource "events" in API group "" at the cluster scope
E0217 15:57:36.168713       1 kubernetes_source.go:110] Failed to load events: events is forbidden: User "system:serviceaccount:kube-system:kube-eventer" cannot list resource "events" in API group "" at the cluster scope
E0217 15:57:37.169582       1 kubernetes_source.go:110] Failed to load events: events is forbidden: User "system:serviceaccount:kube-system:kube-eventer" cannot list resource "events" in API group "" at the cluster scope
E0217 15:57:38.170320       1 kubernetes_source.go:110] Failed to load events: events is forbidden: User "system:serviceaccount:kube-system:kube-eventer" cannot list resource "events" in API group "" at the cluster scope
E0217 15:57:39.171136       1 kubernetes_source.go:110] Failed to load events: events is forbidden: User "system:serviceaccount:kube-system:kube-eventer" cannot list resource "events" in API group "" at the cluster scope
E0217 15:57:40.172081       1 kubernetes_source.go:110] Failed to load events: events is forbidden: User "system:serviceaccount:kube-system:kube-eventer" cannot list resource "events" in API group "" at the cluster scope
E0217 15:57:41.172844       1 kubernetes_source.go:110] Failed to load events: events is forbidden: User "system:serviceaccount:kube-system:kube-eventer" cannot list resource "events" in API group "" at the cluster scope
E0217 15:57:42.173695       1 kubernetes_source.go:110] Failed to load events: events is forbidden: User "system:serviceaccount:kube-system:kube-eventer" cannot list resource "events" in API group "" at the cluster scope

**Comment by ringtail** [comment]
`kubectl get apiservice`看一下 `rbac.authorization.k8s.io/v1`的版本是否匹配。另外可以试下kubectl apply的方式部署，可能是因为dashboard没有支持这个对象的下发

**Comment by liyin37** [comment]
root@k8snode-0001:~# kubectl get apiservice
NAME                                   SERVICE                         AVAILABLE   AGE
v1.                                    Local                           True        69d
v1.apps                                Local                           True        69d
v1.authentication.k8s.io               Local                           True        69d
v1.authorization.k8s.io                Local                           True        69d
v1.autoscaling                         Local                           True        69d
v1.batch                               Local                           True        69d
v1.coordination.k8s.io                 Local                           True        69d
v1.monitoring.coreos.com               Local                           True        69d
v1.networking.k8s.io                   Local                           True        69d
v1.rbac.authorization.k8s.io           Local                           True        69d
v1.scheduling.k8s.io                   Local                           True        69d
v1.storage.k8s.io                      Local                           True        69d
v1alpha1.argoproj.io                   Local                           True        45d
v1alpha1.authentication.istio.io       Local                           True        69d
v1alpha1.longhorn.rancher.io           Local                           True        69d
v1alpha1.rbac.istio.io                 Local                           True        69d
v1alpha2.config.istio.io               Local                           True        69d
v1alpha3.networking.istio.io           Local                           True        69d
v1beta1.admissionregistration.k8s.io   Local                           True        69d
v1beta1.apiextensions.k8s.io           Local                           True        69d
v1beta1.apps                           Local                           True        69d
v1beta1.authentication.k8s.io          Local                           True        69d
v1beta1.authorization.k8s.io           Local                           True        69d
v1beta1.batch                          Local                           True        69d
v1beta1.certificates.k8s.io            Local                           True        69d
v1beta1.coordination.k8s.io            Local                           True        69d
v1beta1.events.k8s.io                  Local                           True        69d
v1beta1.extensions                     Local                           True        69d
v1beta1.longhorn.io                    Local                           True        69d
v1beta1.metrics.k8s.io                 monitoring/prometheus-adapter   True        69d
v1beta1.networking.k8s.io              Local                           True        69d
v1beta1.node.k8s.io                    Local                           True        69d
v1beta1.policy                         Local                           True        69d
v1beta1.rbac.authorization.k8s.io      Local                           True        69d
v1beta1.scheduling.k8s.io              Local                           True        69d
v1beta1.security.istio.io              Local                           True        69d
v1beta1.storage.k8s.io                 Local                           True        69d
v1beta2.apps                           Local                           True        69d
v2beta1.autoscaling                    Local                           True        69d
v2beta2.autoscaling                    Local                           True        69d
v3.cluster.cattle.io                   Local                           True        69d

使用apply我马上测试看下
root@k8snode-0001:~# kubectl apply -f enveter.yaml
deployment.apps/kube-eventer created
clusterrole.rbac.authorization.k8s.io/kube-eventer created
clusterrolebinding.rbac.authorization.k8s.io/kube-eventer created
Warning: kubectl apply should be used on resource created by either kubectl create --save-config or kubectl apply
serviceaccount/kube-eventer configured

我模拟了下告警，但钉钉没有收到任何信息
root@k8snode-0001:~# echo "Error trying v2 registry: failed to register layer: rename /var/lib/docker/image/test /var/lib/docker/image/ddd: directory not empty.*" |systemd-cat -t docker

**Comment by liyin37** [comment]
看pod已经启动并运行，看pod日志如下：
I0218 03:36:59.595575       1 eventer.go:68] kube-eventer version: v1.1.0 commit: 63e7f98
I0218 03:36:59.596365       1 eventer.go:94] Starting with DingTalkSink sink
I0218 03:36:59.596380       1 eventer.go:108] Starting eventer
I0218 03:36:59.596384       1 eventer.go:116] Starting eventer http service
I0218 03:37:00.000116       1 manager.go:102] Exporting 1 events
I0218 03:37:30.000112       1 manager.go:102] Exporting 0 events
I0218 03:38:00.000115       1 manager.go:102] Exporting 1 events
I0218 03:38:30.000108       1 manager.go:102] Exporting 1 events
这个应该是正常了吧，钉钉机器人我使用的是加签的方式
测试curl 钉钉也能收到信息

**Comment by ringtail** [comment]
ok，那问题应该解决了对吧，可以关闭这个issue了吗

**Comment by liyin37** [comment]
没有解决，eventer在k8s中运行没有问题，我研究了很久，在钉钉中，根据https://ding-doc.dingtalk.com/doc#/serverapi2/qf2nxq ，有3种设置方式：
我之前使用ip段的方式，不论如何都无法收到告警信息
现在是暂时使用自定义关键词和 --sink中的label 一致才可以

**Comment by ringtail** [comment]
> 没有解决，eventer在k8s中运行没有问题，我研究了很久，在钉钉中，根据https://ding-doc.dingtalk.com/doc#/serverapi2/qf2nxq ，有3种设置方式：
> 我之前使用ip段的方式，不论如何都无法收到告警信息
> 现在是暂时使用自定义关键词和 --sink中的label 一致才可以

可以关闭加签的方式，默认不启动安全策略即可

**Comment by ringtail** [comment]
或者加签关键字和label一致

**Comment by liyin37** [comment]
现在钉钉机器人默认至少选择一种认知方式
现在是使用加签关键字和label一致 正常了
但使用ip的方式这个要配置那个ip或者ip段呢，写k8s的公网出口ip不行，奇怪

**Comment by ringtail** [comment]
SNAT的IP吗

**Comment by liyin37** [comment]
我是使用华为云服务器使用rancher 搭建k8s集群，每个节点都有绑定公网ip，我在钉钉中写的是一个C段地址，这个应该没有错吧

**Comment by ringtail** [comment]
简单的可以通过这种方式测试，在kube-eventer的pod中`curl ip.cn`看下出口IP

**Comment by liyin37** [comment]
kube-eventer中没有curl命令，还有其他测试方式吗，谢谢

**Comment by ringtail** [comment]
`wget -qO - ip.3322.net`

**Comment by liyin37** [comment]
好的，经测试出口ip和服务器绑定的ip确实不一样，奇怪，谢谢
