### ISSUE TITLE
sink配置为es，日志没有报错，但es没有收到数据

### ISSUE THREAD

**Issue by shijieqin** [AliyunContainerService/kube-eventer#65]
es版本为7.2，日志没有报错，正常创建索引且日志显示正常上报数据，但是es对应索引没有数据

**Comment by ringtail** [comment]
有更多的信息可以提供吗，日志可以贴一下吗

**Comment by NUCsimple** [comment]
> es版本为7.2，日志没有报错，正常创建索引且日志显示正常上报数据，但是es对应索引没有数据

方便发下启动参数吗？ES的日志也麻烦贴下吧
