### ISSUE TITLE
sink为钉钉，发现同一个mesaage的报警次数有20-30次重复。

### ISSUE THREAD

**Issue by zhangshunping** [AliyunContainerService/kube-eventer#66]
kube-eventer配置如下：
     image: registry.aliyuncs.com/acs/kube-eventer-amd64:v1.1.0-c93a835-aliyun
     command:  
            - "/kube-eventer"
            - --frequency=10s
            - --stderrthreshold=10
            - "--source=kubernetes:https://kubernetes.default"
            -   --sink=dingtalk:https://oapi.dingtalk.com/robot/send?access_token=
XXXXXX&level=Warning&namespaces=kube-system,default&label=Pre-k8s&kinds=Pod

发现同一个Waring信息的发送次数有20几条。

**Comment by ringtail** [comment]
麻烦贴一下是否是不同的Pod uid产生的

**Comment by zhangshunping** [comment]
> 麻烦贴一下是否是不同的Pod uid产生的
你好，都是同一个pod的
![image](https://user-images.githubusercontent.com/31233045/75544763-9798fc00-5a5f-11ea-9d97-7ff7cbc2e62f.png)
![image](https://user-images.githubusercontent.com/31233045/75544783-9ff13700-5a5f-11ea-9e32-d407e96ef9a3.png)
![image](https://user-images.githubusercontent.com/31233045/75544797-a7184500-5a5f-11ea-9f34-c5fc872a8518.png)

**Comment by ringtail** [comment]
eventer没有部署多副本吧

**Comment by zhangshunping** [comment]
> eventer没有部署多副本吧

你好，没有多部署，只有一个pod在运行。
![image](https://user-images.githubusercontent.com/31233045/75548921-53125e00-5a69-11ea-878f-3638daadc71f.png)
我运行一个request过大的pod，这是kube-event得日志
![image](https://user-images.githubusercontent.com/31233045/75548985-8c4ace00-5a69-11ea-8184-a272338b520d.png)

**Comment by zhangshunping** [comment]
> eventer没有部署多副本吧
是否是程序bug？

**Comment by ringtail** [comment]
前面大部分是有不同的时间戳的，调度器前期的backoff策略是非常快的，只有几个毫秒一致的是有可能有问题的

**Comment by zeusro** [comment]
```go
func export(s core.EventSink, data *core.EventBatch) {
	startTime := time.Now()
	defer func() {
		exporterDuration.
			WithLabelValues(s.Name()).
			Observe(float64(time.Since(startTime)) / float64(time.Millisecond))
	}()
	data.DistinctSameResourceEvent()
	s.ExportEvents(data)
}

//DistinctSameResourceEvent : Distinct Events base on involvedObject.Name & event.Reason
func (eventBatch *EventBatch) DistinctSameResourceEvent() {
	tempMap := make(map[string]bool)
	var finalEvents []*kube_api.Event
	for _, event := range eventBatch.Events {
		involvedObject := event.InvolvedObject
		if &involvedObject == nil {
			continue
		}
		resourceName := involvedObject.Name
		reason := event.Reason
		key := resourceName + reason
		if _, contain := tempMap[key]; !contain {
			// fmt.Printf("key: %s \n", key)
			tempMap[key] = true
			finalEvents = append(finalEvents, event)
		}
	}
	if len(finalEvents) > 0 {
		eventBatch.Events = finalEvents
	}
}
```

你可以试试我这个非官方实现,基于 resource name 和reason 丢弃重复事件
