### ISSUE TITLE
[Proposal] Aggregate events with same Ref and Reson

### ISSUE THREAD

**Issue by ringtail** [AliyunContainerService/kube-eventer#68]
Due to #66 #42 . We decide to support aggregate events with same ref and reason. This is especially when you have a very large deployment can not be scheduled because of some reasons such as lack of resource.
```
deployment A - >
       Pod A 
       Pod B 
       Pod C 
       ... 
       Pod Z
``` 
There would be so many events emitted.
```
Name: Pod A Reason: Pending Ref: Deploy A Message: inefficient cpu
Name: Pod B Reason: Pending Ref: Deploy A Message: inefficient cpu
Name: Pod C Reason: Pending Ref: Deploy A Message: inefficient cpu
...
Name: Pod Z Reason: Pending Ref: Deploy A Message: inefficient cpu
```
This proposal would aggregate event in on batch like below
```
Name: Pod A and other 25 Pods Reason: Pending Ref: Deploy A Message: inefficient cpu
```

**Comment by zeusro** [comment]
我觉得可以关掉了~

![image](https://user-images.githubusercontent.com/5803609/77601536-f8740100-6f45-11ea-887b-63813ebf7471.png)
