### ISSUE TITLE
社区已经有了为什么还要重复造轮子

### ISSUE THREAD

**Issue by xigang** [AliyunContainerService/kube-eventer#7]
https://github.com/heptiolabs/eventrouter

**Comment by ringtail** [comment]
> https://github.com/heptiolabs/eventrouter
kube-eventer并不是全新的开源项目，是从Heapster的eventer中进行剥离的项目，eventrouter也是当年从heapster中剥离的子项目，我们在Heapster deprecated之前就已经在维护eventer了，Heapster归档后，我们就将原有的功能进行了剥离，独立维护了eventer，这样以前依赖Heapster eventer的客户可以继续按照原来的用法使用eventer，我们会继续维护已经存在的sink，提供社区的保证。

**Comment by ringtail** [comment]
这是原来的子项目，https://github.com/kubernetes-retired/heapster/tree/master/events，目前云上有大量的客户依然在依赖这个子项目，我们在和社区商讨后，决定剥离子项目，独立成为kube-eventer，继续为社区和开发者维护。

**Comment by ringtail** [comment]
有兴趣可以看看过去的一些讨论：
https://github.com/heptiolabs/eventrouter/issues/26 
https://github.com/kubernetes-retired/heapster/pull/2089

**Comment by xigang** [comment]
> 这是原来的子项目，[https://github.com/kubernetes-retired/heapster/tree/master/events。](https://github.com/kubernetes-retired/heapster/tree/master/events%E3%80%82)
> 目前云上有大量的客户依然在依赖这个子项目，我们在和社区商讨后，决定剥离子项目，独立成为kube-eventer，继续为社区和开发者维护。

为了兼容其它客户已有的使用习惯，把项目剥离出来也好：）
