### ISSUE TITLE
[Proposal] Remove honeycomb from kube-eventer

### ISSUE THREAD

**Issue by ringtail** [AliyunContainerService/kube-eventer#80]
Honeycomb is the lowest frequency of use.  Remove it in progress.

**Comment by henrywu2019** [comment]
Why not just keep it in case somebody needs it indeed?

**Comment by ringtail** [comment]
@henrywu2019 There is no maintainer of these sinks left. We have no idea about the issue and pr about these two sinks.

**Comment by ringtail** [comment]
If no one using these two sinks. We would like to remove them since next version.

**Comment by henrywu2019** [comment]
I can maintain it. I use honeycomb. :-)

**Comment by ringtail** [comment]
@henrywu2019 Sure ! Thanks man.
