### ISSUE TITLE
 镜像无法拉取

### ISSUE THREAD

**Issue by sober-wang** [AliyunContainerService/kube-eventer#81]
```shell
docker pull registry.aliyuncs.com/acs/kube-eventer-amd64:v1.1.0-c93a835-aliyun
```
提示：
Error response from daemon: Get https://registry.aliyuncs.com/v2/acs/kube-eventer-amd64/manifests/latest: Get https://dockerauth.cn-hangzhou.aliyuncs.com/auth?scope=repository%3Aacs%2Fkube-eventer-amd64%3Apull&service=registry.aliyuncs.com%3Acn-hangzhou%3A26842: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

麻烦重新提供一下镜像地址，谢谢。

**Comment by zeusro** [comment]
docker pull registry.aliyuncs.com/acs/kube-eventer-amd64:v1.1.0-c93a835-aliyun

v1.1.0-c93a835-aliyun: Pulling from acs/kube-eventer-amd64
f4ea4c4069ac: Pull complete
28249749420a: Pull complete
e0b429f22e5c: Pull complete
0b2d0ffa3a2a: Pull complete
d243afc0e53a: Pull complete
Digest: sha256:457730a7298f7ec713752b21f759fc4a34d79f5eaedc39bf6a68e72af4406ad9
Status: Downloaded newer image for registry.aliyuncs.com/acs/kube-eventer-amd64:v1.1.0-c93a835-aliyun
registry.aliyuncs.com/acs/kube-eventer-amd64:v1.1.0-c93a835-aliyun

**Comment by ringtail** [comment]
> ```shell
> docker pull registry.aliyuncs.com/acs/kube-eventer-amd64:v1.1.0-c93a835-aliyun
> ```
> 
> 提示：
> Error response from daemon: Get https://registry.aliyuncs.com/v2/acs/kube-eventer-amd64/manifests/latest: Get https://dockerauth.cn-hangzhou.aliyuncs.com/auth?scope=repository%3Aacs%2Fkube-eventer-amd64%3Apull&service=registry.aliyuncs.com%3Acn-hangzhou%3A26842: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
> 
> 麻烦重新提供一下镜像地址，谢谢。

是否可以本机验证下，这个地址是公网的，麻烦确认下网络连通性。

**Comment by sober-wang** [comment]
> 
> 
> > ```shell
> > docker pull registry.aliyuncs.com/acs/kube-eventer-amd64:v1.1.0-c93a835-aliyun
> > ```
> > 
> > 
> > 提示：
> > Error response from daemon: Get https://registry.aliyuncs.com/v2/acs/kube-eventer-amd64/manifests/latest: Get https://dockerauth.cn-hangzhou.aliyuncs.com/auth?scope=repository%3Aacs%2Fkube-eventer-amd64%3Apull&service=registry.aliyuncs.com%3Acn-hangzhou%3A26842: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
> > 麻烦重新提供一下镜像地址，谢谢。
> 
> 是否可以本机验证下，这个地址是公网的，麻烦确认下网络连通性。

联通性没有问题，我 pull nginx,centos 镜像都是可以的。唯独这个镜像超时。
