### ISSUE TITLE
Why the copyright of this project is belong to Google Inc

### ISSUE THREAD

**Issue by mozillazg** [AliyunContainerService/kube-eventer#82]
Each go file has a notice:

```
Copyright <year> Google Inc. All Rights Reserved.
```

Does this project was forked from a project which was open sourced by Google Inc?

**Comment by ringtail** [comment]
This Project is from a sub project of kubernetes/heapster. So keep the Copyright before.

**Comment by mozillazg** [comment]
Got it. Thanks for your reply.
