### ISSUE TITLE
[WIP] 是否可以添加支持 Slack，Mattermost，Rocket 的消息推送

### ISSUE THREAD

**Issue by lushenle** [AliyunContainerService/kube-eventer#90]
是否可以添加支持 `Slak`，`Mattermost`，`Rocket` 的消息推送？目前不能直接就 `events` 直接推送到这个 Slack 或者 Mattermost，Rocket 这样的工具的某个 `channel`。希望能增加将 `Mattermost` 支持，如果可以，其余二者增加就更好。

**Comment by zeusro** [comment]
欢迎PR

https://github.com/AliyunContainerService/kube-eventer/tree/master/sinks

**Comment by ringtail** [comment]
@lushenle 这块目前的计划是会统一推出通用Webhook的机制，支持客户自定义请求方法、Body、鉴权方式。用泛化的方式支持上述能力。

**Comment by ringtail** [comment]
@lushenle 另外[WIP]表示Work In Process，你的Code已经在开发了吗。

**Comment by ringtail** [comment]
Link to #86
