### ISSUE TITLE
watch/list消息有延时

### ISSUE THREAD

**Issue by zehuaiWANG** [AliyunContainerService/kube-eventer#97]
发现实际告警时间和last_occurrence_time有较大延时（有时会多达一个小时）

**Comment by ringtail** [comment]
是哪一种告警方式。

**Comment by zehuaiWANG** [comment]
应该是一个同步问题，我猜测这样的。event在etcd中默认存一小时，然后在刚好满一小时的时候，如果event删除和sync同时发生，这时候就有可能会多出一条重复的event。你遇到过这种情况？跟告警方式没啥关系。

**Comment by ringtail** [comment]
@zehuaiWANG eventer默认是周期性拉取event，event在etcd是按条存储的，过期的单位是条，因此不会出现批量全量删除的场景。

**Comment by zehuaiWANG** [comment]
是的，我的意思是某一条或几条会出现重复。
